pkg/controller/gitopsservice/gitopsservice_controller.go
Add support for creating SSL certs for services and mounting them into the container.
=> Support for certs and mounting them.

README.md
OPERATOR_NAME=gitops-operator operator-sdk run local --watch-namespace=openshift-pipelines-app-delivery
=> fix watch command

OWNERS
=> Update root owner file

scripts/openshiftci-presubmit-all-tests.sh, scripts/openshiftci-presubmit-unittests.sh
Adding scripts for all-tests and unit-tests
=> Adding scripts for all-tests and unit-tests

openshift-ci/build-root/source-image/Dockerfile
Adding Dockerfile to copy the oc binary
=> Adding Dockerfile to copy the oc binary

OWNERS
I keep getting my review requested on this project I'm no longer a part of. 😭
=> Remove me from owners ☹️

README.md, pkg/controller/gitopsservice/gitopsservice_controller.go, test/e2e/gitops_service_test.go
instead of openshift-pipelines-app-delivery
=> Use openshift-gitops namespace

go.mod, go.sum
Pick up latest argocd operator including "expose api for cluster config"
=> Pick up latest argocd operator including "expose api for cluster config"

deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml, deploy/operator.yaml
Use https://github.com/argoproj-labs/argocd-operator/blob/8aa14c03df16b634d6f01ac309f727f8645a6c4e/pkg/reconciler/openshift/openshift.go#L21
=> env var for cluster config in deployment manifest

pkg/controller/gitopsservice/gitopsservice_controller.go
remove duplicate declaration of variable caused by bad merge
=> remove duplicate declaration of variable caused by bad merge

go.mod, go.sum
Picks up following fixes - 
https://github.com/argoproj-labs/argocd-operator/pull/241
https://github.com/argoproj-labs/argocd-operator/pull/242
=> pick up reconcile redis/dex fixes from upstream argocd operator

pkg/controller/util/util.go, scripts/openshiftci-presubmit-unittests.sh
Add unit test target in OpenShift CI
=> Add unit test target in OpenShift CI

Makefile, scripts/install-operator-sdk.sh, scripts/openshiftci-presubmit-all-tests.sh, scripts/prepare-test-cluster.sh
Enable gitops e2e test on OpenShift CI
=> Enable gitops e2e test

deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml
/kind bug
Fix spacing that caused the CSV doc to be invalid
Fixes #?
Test build operator bundle with the fixed CSV
=> fix spacing

test/e2e/kam_test.go
Fix comments in operator e2e tests
Signed-off-by: Chetan Banavikalmutt <chetanrns1997@gmail.com>
=> Fix comments in e2e test

deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml
/kind code-refactoring
https://issues.redhat.com/browse/GITOPS-650
Fixes #?
create a custom GitOps Operator Bundle. Follow the ReadMe. Install the Custom GitOps Operator.
Then  click on the Installed Gitops Operator->ArgoCD->Create ArgoCD->Server->Route 
You will see the route is enabled.
=> GITOPS-650 - added ArgoCD CR example to add route in GitOps Operator CSV

go.mod, openshift-ci/build-root/Dockerfile
/kind cleanup
go version should match with https://github.com/redhat-developer/gitops-operator/blob/master/Dockerfile#L1
Fixes NA
go version reference should be same across the codebase
=> Sync go version

README.md
Update introduction in the readme
=> Update introduction in the readme

deploy/crds/argoproj.io_applicationsets_crd.yaml, deploy/crds/argoproj.io_argocds_crd.yaml, deploy/olm-catalog/gitops-operator/manifests/argoproj.io_applicationsets_crd.yaml, deploy/olm-catalog/gitops-operator/manifests/argoproj.io_argocds_crd.yaml, deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml, pkg/controller/argocd/argocd.go
Adds ApplicationSet Controller CRDs, ensures a default instance is created, and updates the CSV to include the CRD version
Fixes #?
=> Add ApplicationSet controller to gitops-operator

scripts/openshiftci-presubmit-all-tests.sh, scripts/openshiftci-presubmit-unittests.sh
/kind cleanup
Remove unnecessary environment variable
Fixes #?
N/A
=> Removing unnecessary environment variable

deploy/crds/argoproj.io_argocds_crd.yaml, deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml, go.mod, go.sum, pkg/controller/argocd/argocd.go, pkg/controller/argocd/argocd_test.go
#92 
GITOPS-823
No
Fixes #92 
GITOPS-823
Create a namespace with resource quota as mentioned in the below link
https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/quota-memory-cpu-namespace/
Install argo cd from the openshift console in the namespace created above.
=> feat: set default requests and limits (#92)

test/examples/scheduler/scheduler-config.yaml, test/yamls/scheduler_appcr.yaml
Need to add the files for testing the https://github.com/redhat-developer/gitops-operator/pull/135. As it checks for the yamls in a particular folder in the gitops-operator.
Fixes #?
=> adding yaml files for cluster config e2e 

test/examples/identity-provider/identity-provider.yaml, test/yamls/identity-provider_appcr.yaml
> /kind bug
Adds new identity-provider and application CR yamls for e2e tests
Fixes #?
=> added identity-provider and application cr yamls for e2e test 

go.mod, go.sum
> /kind bug
fixes #143 
NA
#143 
Run e2e tests locally.
Run e2e tests locally. This PR should fix the local failure
=> fix: e2e tests failing locally (#143)

test/appcrs/identity-provider_appcr.yaml, test/appcrs/image_appcr.yaml, test/appcrs/scheduler_appcr.yaml
=> Adding application CRs to appcrs directory

test/appcrs/scheduler_appcr.yaml, test/e2e/gitops_service_test.go, test/helper/application_status.go, test/rolebindings/role-binding.yaml, test/rolebindings/role.yaml
What type of PR is this?
What does this PR do / why we need it:
This PR add the following test case.
Create an argocd application CR that has source folder containing a manifest of an config map in openshift-config project
oc apply -f the argocd application CR
Verify that the openshift cluster-config resource is deployed. Verify that the argocd application is healthy and sync'ed.
Have you updated the necessary documentation?
Documentation update is required by this PR.
Documentation has been updated.
Which issue(s) this PR fixes:
Fixes - https://issues.redhat.com/browse/GITOPS-1003
Test acceptance criteria:
Unit Test - NA
E2E Test
How to test changes / Special notes to the reviewer:
=> e2e test for cluster config change - GITOPS-1003

test/appcrs/nginx_appcr.yaml, test/examples/nginx/nginx.yaml
Add a namespace scoped example to be consumed in the e2e tests
Fixes #?
=> add a namespace scoped example for e2e

test/appcrs/nginx_default_ns_appcr.yaml
> /kind bug
adds an nginx app cr in openshift-gitops namespace for GITOPS-1004 test scenario 
Fixes #?
=> add nginx appcr in openshift-gitops for e2e test

deploy/olm-catalog/gitops-operator/manifests/argoproj.io_applications_crd.yaml, deploy/olm-catalog/gitops-operator/manifests/argoproj.io_applicationsets_crd.yaml, deploy/olm-catalog/gitops-operator/manifests/argoproj.io_appprojects_crd.yaml, deploy/olm-catalog/gitops-operator/manifests/argoproj.io_argocds_crd.yaml, go.mod, go.sum
> /kind bug
Fixes #?
Please refer to https://github.com/argoproj-labs/argocd-operator/pull/358
=> Sync argocd operator to pick up: Add ability to specify Repo server image and tag (#358)

deploy/crds/argoproj.io_argocds_crd.yaml, go.mod, go.sum
* https://github.com/argoproj-labs/argocd-operator/pull/364 ( fix: Allow reconciliation of resource overrides #364 )
* https://github.com/argoproj-labs/argocd-operator/pull/360 ( feat: Add ability to apply additional labels to generated routes #360 )
/kind bug
Fixes #?
Please refer to PRs. …
=> Pull the floowing fixes from argocd-operator: #364, #360

go.mod, go.sum
=> chore: fix runc security vulnerability reported by dependabot

LICENSE
=> chore: Add Apache 2.0 License

test/e2e/argocd_metrics_test.go
https://issues.redhat.com/browse/GITOPS-1007
Fixes - https://issues.redhat.com/browse/GITOPS-1007
```make test-e2e``` should pass
=> Update monitoring e2e test coverage

Makefile
To run specific gitops feature testing through make targets
Fixes #?
```
make test-metrics
make test-route
make test-gitopsservice
make test-gitopsservice-nondefault
```
=> Add individual test target

main.go
> /kind bug
Fixes: #199 
Fixes #?
=> Import openshift package from argocd-operator to enable hooks

Makefile, README.md, bundle/manifests/gitops-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml
Update the docs with the latest Makefile targets generated by operator-sdk
Fixes #?
=> Replace commands in the README with Makefile targets

README.md
Fixes up the README file, documentation had some errors. Content is still all essentially the same.
=> fix some grammar errors/typos in README file

controllers/gitopsservice_controller.go, test/e2e/gitopsservice_test.go
The backend service should have permission to read secrets in order to communicate w
Fixes #?
=> Allow backend service role to access secrets

go.mod, go.sum
Pull in bug fixes from argocd-operator's rhos-v1.2 branch in preparation for GitOps v1.2.1
* https://issues.redhat.com/browse/GITOPS-1255
* https://issues.redhat.com/browse/GITOPS-1300
* https://issues.redhat.com/browse/GITOPS-1247
* https://issues.redhat.com/browse/GITOPS-1274
=> Update argocd-operator to latest changes in rhos-v1.2 branch

README.md
Updates the steps to run operator locally. The current documentation does not explain the steps to install the CRDs before running the operator locally.
NA
=> chore: update steps to run operator locally

bundle/manifests/argoproj.io_applicationsets.yaml, bundle/manifests/argoproj.io_argocds.yaml, config/crd/bases/argoproj.io_applicationsets.yaml, config/crd/bases/argoproj.io_argocds.yaml
> /kind bug
This PR copies the following CRDs from argocd-operator.  They are out of sync.
* argocdproj.io_applicationsets.yaml
* argocdproj.io_argocds.yaml
n/a
Fixes #?
=> Sync up CRDs from upstream argocd operator

go.mod, go.sum
Pull in https://github.com/argoproj-labs/argocd-operator/pull/444 from argocd-operator
Fixes #?
=> Pull in changes from argocd-operator

bundle/manifests/argoproj.io_argocds.yaml, config/crd/bases/argoproj.io_argocds.yaml, go.mod, go.sum, test/e2e/gitopsservice_test.go
> /kind bug
Picks up multiple sso configuration validation from argocd-operator 
N/A
=> chore: pickup multiple sso validation

bundle/manifests/argoproj.io_applicationsets.yaml, config/crd/bases/argoproj.io_applicationsets.yaml
/kind bug
This PR update the applicationset crd to v0.2.0
Fixes #?
=> update applicationset crd to v0.2.0

bundle/manifests/gitops-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/gitopsservice_controller.go
> /kind bug
Fixes #236 
Fixes #236 
NA
NA
=> fix: add missing oauthclient permissions [cherry-pick into v1.3]

bundle/manifests/gitops-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/gitopsservice_controller.go
> /kind bug
Fixes #236 
Fixes #236 
NA
NA
=> fix: add missing oAuthClient permissions

go.mod, go.sum
> /kind bug
Picks up bug fixes for v1.3.2 from the rhos-v1.3 branch of argocd-operator 
Fixes #?
=> pick-up 1.3.2 bug fixes 

go.mod, go.sum
pick latest of rhos-v1.3
NA
NA
=> chore: pick latest from argocd-operator rhos-v1.3

bundle/manifests/gitops-operator.clusterserviceversion.yaml, config/manifests/bases/gitops-operator.clusterserviceversion.yaml
update `support` and `repository` details in the csv. currently the fields are empty.
NA
=> chore: add repo url and support to csv

README.md
Differences between GitOps operator and Argo CD community Operator
Matrix with differences between community and official GitOps Operator
Fixes [GITOPS-1113](https://issues.redhat.com/browse/GITOPS-1113)
=> doc: Differences between the GitOps operator and Argo CD community operator

bundle/manifests/argoproj.io_applications.yaml, bundle/manifests/argoproj.io_argocds.yaml, config/crd/bases/argoproj.io_applications.yaml, config/crd/bases/argoproj.io_argocds.yaml, go.mod, go.sum
> /kind bug
chore: add missing application CRD changes
Application CRD should be in sync with the CRD in Argo CD upstream v2.3 branch.
https://github.com/argoproj/argo-cd/blob/release-2.3/manifests/crds/application-crd.yaml
=> chore: add missing application CRD changes for v1.5 branch

bundle/manifests/argoproj.io_appprojects.yaml, config/crd/bases/argoproj.io_applicationsets.yaml, config/crd/bases/argoproj.io_appprojects.yaml
/kind chore
chore: add missing appproject CRD changes
Fixes #?
AppProject CRD should be in sync with the CRD in Argo CD upstream v2.3.3 branch.
https://github.com/argoproj/argo-cd/blob/v2.3.3/manifests/crds/appproject-crd.yaml
=> chore: add missing appproject CRD changes for v1.5 branch

.ci-operator.yaml
=> Adding .ci-operator file

Makefile
Signed-off-by: rishabh625 <rishabhmishra625@gmail.com>
> /kind bug
Fixes #?
=> reverted ls and fix read go version

openshift-ci/build-root/Dockerfile
Signed-off-by: rishabh625 <rishabhmishra625@gmail.com>
> /kind bug
Fixes #?
=> changed Dockerfile to 1.18

Makefile
Signed-off-by: rishabh625 <rishabhmishra625@gmail.com>
> /kind bug
Fixes #?
=> set empty goflag for 1.18

go.mod, go.sum
=> chore: update argocd-operator dependency

go.mod, go.sum
/kind cleanup
Updates to the latest version of the release-0.4 branch of the argocd operator
Fixes #?
=> Update argocd-operator depenedency

go.mod, go.sum
/kind bug
Update argocd-operator version to pick up backported fixes
Fixes #?
=> fix: backport 4.11 fixes to v1.4

go.mod, go.sum
/kind bug
Backport fixes for OCP 4.11 to v1.5
Fixes #?
=> fix: backport 4.11 fixes to v1.5

docs/OpenShift GitOps Usage Guide.md
=> docs: update infra nodes doc in usage guide

docs/OpenShift GitOps Usage Guide.md
> /kind bug
Adds instructions for managing machinesets with Argo CD using server-side apply within the GitOps Usage guide
Fixes https://issues.redhat.com/browse/GITOPS-1918
=> docs: Update usage guide with instructions to manage machinesets

.gitignore
add .vscode/ to .gitignore
> /kind bug
Fixes #?
=> add .vscode/ to .gitignore

bundle/manifests/argoproj.io_argocds.yaml, config/crd/bases/argoproj.io_argocds.yaml, go.mod, go.sum, test/e2e/gitopsservice_test.go
Pulls https://github.com/argoproj-labs/argocd-operator/commit/8a80d94ba5b4282f14e7922fb79f1c9c4f9f447f and https://github.com/argoproj-labs/argocd-operator/commit/5501a7963b91468c25fde95668b7ade49ea2f346
NA
=> [v1.6] Pull latest from upstream

bundle/manifests/argoproj.io_argocds.yaml, config/crd/bases/argoproj.io_argocds.yaml, go.mod, go.sum
Pulls https://github.com/argoproj-labs/argocd-operator/commit/5e9e50f90bf5746853885950e50ef3ab1ae95e9a and https://github.com/argoproj-labs/argocd-operator/commit/30731f997458f9a28051edddca4741be274d93e9
=> [v1.5] Pull latest from upstream

bundle/manifests/argoproj.io_argocds.yaml, config/crd/bases/argoproj.io_argocds.yaml, go.mod, go.sum
Pulls https://github.com/argoproj-labs/argocd-operator/commit/05b30e76f170a1cfaabe6b09169e3db9e27ada33 and https://github.com/argoproj-labs/argocd-operator/commit/87f757a12041e863f93b29eee710463f07ba53c0
=> [v1.4] Pull latest from upstream

go.mod, go.sum
> /kind bug
consumes latest commit in 0.4 release branch to pick up sso deprecation event emission fixes for 1.6.2
Fixes #?
=> chore: consume latest commit in release-0.4 branch

controllers/argocd_controller.go, controllers/argocd_controller_test.go, controllers/kam.go, controllers/util/util.go, main.go, test/e2e/suite_test.go, test/nondefaulte2e/suite_test.go
Support console api being optional
> /kind bug
Fixes #?
=> Optional console link 1.6

controllers/argocd_controller.go, controllers/argocd_controller_test.go, controllers/kam.go, controllers/util/util.go, main.go, test/e2e/suite_test.go, test/nondefaulte2e/suite_test.go
Support console api being optional
> /kind bug
Fixes #?
=> Optional console link 1.5

controllers/argocd_controller.go, controllers/argocd_controller_test.go, controllers/kam.go, controllers/util/util.go, main.go, test/e2e/suite_test.go, test/nondefaulte2e/suite_test.go
Support console api being optional
> /kind bug
Fixes #?
=> Optional console link 1.4

go.mod, go.sum
> /kind bug
pull latest commit from release-0.4 branch of argocd-operator
Fixes #?
=> chore: pull latest commit from release-0.4 branch

docs/OpenShift GitOps Usage Guide.md
=> docs: add nodeSelector feature to the docs

bundle/manifests/gitops-operator.clusterserviceversion.yaml, bundle/manifests/pipelines.openshift.io_gitopsservices.yaml, config/rbac/role.yaml, controllers/argocd_metrics_controller.go, controllers/gitopsservice_controller.go
Signed-off-by: saumeya <saumeyakatyal@gmail.com>
/kind bug
Removed duplicated and wildcards in role.yaml config file
Fixes GITOPS-2350
=> fix: update role wildcards in rbac file

bundle/manifests/gitops-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/rbac/role.yaml, controllers/gitopsservice_controller.go, go.mod, go.sum
/kind bug
The build was failing due to insufficient permissions in the rbac api group(Due to removal of wildcards in previous PR #388 ). Added the missing permissions
Also update the argocd-operator commit sha to latest.
Fixes #?
=> fix: update rbac.authorization verbs, update argocd sha

go.mod, go.sum
Signed-off-by: rjeczkow [rjeczkow@gmail.com](mailto:rjeczkow@gmail.com)
/kind bug
Setting ContainerPort for ApplicationSet container to 8080 in order to make it consistent with the ApplicationSet service TargetPort
https://issues.redhat.com/browse/GITOPS-2411
Fixes #?
=> fix: applicationset container port for metrics

bundle/manifests/argoproj.io_argocds.yaml, config/crd/bases/argoproj.io_argocds.yaml
Adds missing CRD changes for Notifications ENV and IngressClass
=> feat: add missing CRD changes for Notifications ENV and IngressClass

go.mod, go.sum
> /kind bug
updates the consumed argocd-operator commit to pick up required changes to support apps-in-any-namespaces
Fixes #?
=> chore: pickup latest argocd-operator commit 

go.mod, go.sum
Signed-off-by: ishitasequeira <ishiseq29@gmail.com>
**What type of PR is this?*
update argocd-operator commit
Fixes #?
=> chore: pick up latest argocd-operator commit

common/common.go, controllers/gitopsservice_controller.go, controllers/gitopsservice_controller_test.go, go.mod, go.sum
Signed-off-by: Yi Cai <yicai@redhat.com>
cherry-pick #402 
Please refer #402
=> [cherry-pick]: Add reconcile plugin condition (#402)

bundle/manifests/argoproj.io_argocds.yaml, config/crd/bases/argoproj.io_argocds.yaml
=> chore: fix accidental removal of sourceNamespaces from CRD

go.mod, go.sum
> /kind bug
Pulls https://github.com/argoproj-labs/argocd-operator/pull/818
NA
Fixes https://github.com/argoproj-labs/argocd-operator/pull/818
Please refer https://github.com/argoproj-labs/argocd-operator/pull/818
=> fix: issues with dex connection failure and wrong ingress hostname in the CR

go.mod, go.sum
Signed-off-by: yicai@redhat.com
**What type of PR is this?*
update argocd-operator commit, it picks up the [commit](https://github.com/argoproj-labs/argocd-operator/commit/10f11b638e42db5d00174ffdc9905dc973e72aaa) for GITOPS-2480
Fixes #?
=> Pick up latest argocd-operator commit

test/openshift/e2e/parallel/1-090_validate_permissions/01-assert.yaml, test/openshift/e2e/sequential/1-031_validate_toolchain/01-check.yaml, test/openshift/e2e/sequential/1-085_validate_dynamic_plugin_installation/02-install-dynamic-plugin.yaml
Signed-off-by: varshab1210 <vab@redhat.com>
/kind cleanup
Updates Kuttl tests for GitOps v1.7.1
Fixes #?
=> Modifying Kuttl tests for v1.7.1

bundle/manifests/argoproj.io_applications.yaml, bundle/manifests/argoproj.io_applicationsets.yaml, bundle/manifests/argoproj.io_argocds.yaml, config/crd/bases/argoproj.io_applications.yaml, config/crd/bases/argoproj.io_applicationsets.yaml, config/crd/bases/argoproj.io_argocds.yaml
pull latest manifests into the gitops operator
NA
=> feat: Add manifest changes from the upstream operator

go.mod, go.sum
Pulls the latest from Argo CD operator
https://github.com/argoproj-labs/argocd-operator/commit/d3798bf52573d12428ee0b62f169ff4094919eb8
=> chore: pull latest version of argo-cd operator

go.mod, go.sum
=> fix: upgrade `goutils` to `v1.1.1` to address CVE-2021-4238 [v1.6]

go.mod, go.sum
Signed-off-by: Jaideep Rao <jaideep.r97@gmail.com>
/kind bug
Fixes #?
=> fix: upgrade `goutils` to `v1.1.1`  to address CVE-2021-4238 [v1.5]

bundle.Dockerfile, bundle/manifests/gitops-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, test/openshift/e2e/parallel/1-090_validate_permissions/01-assert.yaml, test/openshift/e2e/sequential/1-031_validate_toolchain/01-check.yaml, test/openshift/e2e/sequential/1-084_validate_prune_templates/01-assert.yaml, test/openshift/e2e/sequential/1-084_validate_prune_templates/01-create-ns-managed-by.yaml, test/openshift/e2e/sequential/1-084_validate_prune_templates/02-prune-duplicateGVK-resource.yaml, test/openshift/e2e/sequential/1-084_validate_prune_templates/03-errors.yaml, test/openshift/e2e/sequential/1-084_validate_prune_templates/04-delete.yaml
This PR addresses failures detected in Openshift CI checks
Fixes #?
=> Fixing tests for Openshift CI compatibility

bundle/manifests/argoproj.io_applications.yaml, bundle/manifests/argoproj.io_applicationsets.yaml, bundle/manifests/gitops-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, config/default/kustomization.yaml, config/manager/manager.yaml, config/manifests/patches/description.yaml
=> Update bundle for crds and metadata

bundle/manifests/gitops-operator.clusterserviceversion.yaml, config/manifests/patches/description.yaml
Update the description to reflect the latest version of Argo CD. Other changes related to the Argo CD branch details, commit SHA and tag are dealt in the midstream repo.
=> feat: update Argo CD version to 2.6.7

Makefile, README.md, bundle.Dockerfile, bundle/manifests/gitops-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, config/manager/kustomization.yaml, config/manager/manager.yaml, config/manifests/bases/gitops-operator.clusterserviceversion.yaml, config/manifests/kustomization.yaml, scripts/openshiftci-olm-kuttl-tests.sh
=> Changing naming conventions for v1.8

go.mod, go.sum, test/openshift/e2e/parallel/1-098_validate_dex_clientsecret_deprecated/01-assert.yaml, test/openshift/e2e/parallel/1-098_validate_dex_clientsecret_deprecated/01-install.yaml, test/openshift/e2e/parallel/1-098_validate_dex_clientsecret_deprecated/02-verify-clientsecret.yaml
/kind bug
**What does this PR do / why we need it**: https://github.com/argoproj-labs/argocd-operator/pull/877
Fixes #?
=> fix: Reconcile Dex client secret when .spec.dex is set

controllers/gitopsservice_controller.go, controllers/gitopsservice_controller_test.go, controllers/kam.go, controllers/util/util.go
Cherry-pick https://github.com/redhat-developer/gitops-operator/pull/451 
Fixes #?
=> fix: add security context to kam and cluster pods

go.mod, go.sum
Cherry pick https://github.com/redhat-developer/gitops-operator/pull/471
Fixes #?
=> chore: Pull latest version of argo-cd operator 

go.mod, go.sum
=> chore: pick up latest argocd-operator commit for v1.8 branch

scripts/openshift-Interop-kuttl-tests.sh
This PR adds a new script for onboarding interop testing on Openshift CI
Fixes #?
=> Onboading Interop testing on Openshift CI

go.mod, go.sum
=> bug: pickup hpa reconciliation fixes for v1.8.3

test/openshift/e2e/parallel/1-038_validate_productized_images/02-check-images.yaml, test/openshift/e2e/parallel/1-090_validate_permissions/01-assert.yaml, test/openshift/e2e/sequential/1-031_validate_toolchain/01-check.yaml, test/openshift/e2e/sequential/1-085_validate_dynamic_plugin_installation/02-install-dynamic-plugin.yaml
Enabling CI on v1.8 branch would cause some test failure. This PR addresses the same 
Fixes #?
=> CI failure: Fixing Kuttl tests

docs/OpenShift GitOps Usage Guide.md
Follow up PR for https://github.com/argoproj-labs/argocd-operator/pull/911 to update doc to reflect extended support for sso deprecated fields.
Fixes [GITOPS-2904](https://issues.redhat.com/browse/GITOPS-2904)
=> docs: Update doc to reflect extended support for sso deprecated fields

openshift-ci/build-root/Dockerfile
Updating Dockerfile with pre-requisites for 1.7 kuttl tests
Fixes #?
=> update Dockerfile for openshift-ci testing

test/openshift/e2e/sequential/1-018_validate_disable_default_instance/02-patch-subscription.yaml, test/openshift/e2e/sequential/1-034_validate_custom_roles/02-patch-subscription.yaml, test/openshift/e2e/sequential/1-050_validate_sso_config/04-disable-dex-through-sub.yaml, test/openshift/e2e/sequential/1-056_validate_managed-by/04-add_env.yaml
This PR adds a check if the tests are running on CI or on local.
Fixes #?
=> fix test for 1.7

OWNERS
This PR adds QE manager and team members as approvers and reviewers respectively
Fixes #?
=> add QE manager and team members as Approver and Reviewer

test/openshift/e2e/sequential/1-018_validate_disable_default_instance/03-patch-subscription.yaml, test/openshift/e2e/sequential/1-034_validate_custom_roles/06-revert-patch.yaml, test/openshift/e2e/sequential/1-050_validate_sso_config/05-unset-disable-dex-env-var.yaml, test/openshift/e2e/sequential/1-056_validate_managed-by/07-remove_env.yaml
=> fix e2e sequestial failing test

test/openshift/e2e/parallel/1-030_validate_reencrypt/03-check-route.yaml, test/openshift/e2e/parallel/1-066_validate_redis_secure_comm_no_autotls_no_ha/03-create_secret.yaml, test/openshift/e2e/parallel/1-066_validate_redis_secure_comm_no_autotls_no_ha/05-check_deployments.yaml, test/openshift/e2e/sequential/1-042_validate_status_host/03-assert.yaml, test/openshift/e2e/sequential/1-042_validate_status_host/03-modify_route_URL.yaml
=> Fix kuttl tests for v1.7

bundle/manifests/argoproj.io_applications.yaml, bundle/manifests/gitops-operator.clusterserviceversion.yaml, config/crd/bases/argoproj.io_applications.yaml, config/manifests/patches/description.yaml, go.mod, go.sum, test/openshift/e2e/ignore-tests/sequential/1-031_validate_toolchain/01-check.yaml
/kind cleanup
Cherry-picks commits/changes from https://github.com/redhat-developer/gitops-operator/pull/553/files in 1.9 branch which are to: 
- update the CRD's to ArgoCD 2.7.6 
- update clusterserviceversion to 2.7.6
- fix error with valid_toolchain kuttl test
=> Cherry pick 1.9.1

OWNERS
Add @svghadi to reviewers list for v1.8 branch
Closes #570
=> [v1.8] Add Siddhesh to reviewers list

OWNERS
Add @svghadi to reviewers list for v1.7 branch
Closes #570
=> [v1.7] Add Siddhesh to reviewers list

hack/scripts/run-non-olm-kuttl-test.sh
=> fix: non-olm kuttl test script bug fix

bundle/manifests/argoproj.io_applications.yaml, bundle/manifests/argoproj.io_applicationsets.yaml, config/crd/bases/argoproj.io_applications.yaml, config/crd/bases/argoproj.io_applicationsets.yaml
update application and applicationsets crds to match with argo cd v2.8.3
NA
NA
=> feat: update application and applicationsets crds to match with argo cd v2.8.3

go.mod, go.sum
upgrades RH-SSO from 7.5 to 7.6
NA
=> feat: upgrade RH-SSO to 7.6 and fix probes issue

bundle/manifests/argoproj.io_analysisruns.yaml, bundle/manifests/argoproj.io_analysistemplates.yaml, bundle/manifests/argoproj.io_clusteranalysistemplates.yaml, bundle/manifests/argoproj.io_experiments.yaml, bundle/manifests/argoproj.io_rollouts.yaml, go.mod, go.sum, test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml, test/openshift/e2e/parallel/1-090_validate_permissions/01-assert.yaml, test/openshift/e2e/parallel/1-101_validate_rollout_policyrules/01-assert.yaml
> /kind bug
Upgrade rollouts-manager version and crds
Fixes #?
=> chore: update rollouts manager to 0.0.2 with crds

go.mod, go.sum
Pulls in changes from argocd-operator  for https://github.com/argoproj-labs/argocd-operator/pull/1278 
Fixes #?
=> pull in changes from argocd-operator for 1.12 release

bundle/manifests/gitops-operator.clusterserviceversion.yaml, config/manifests/bases/gitops-operator.clusterserviceversion.yaml, config/samples/argoproj.io_v1beta1_argocd.yaml, config/samples/kustomization.yaml
**What type of PR is this?** 
> /kind chore  
**Goal**: Overall increase the quality and presence of vital operator metadata for Red Hat operators to drive up trust and discoverability by customers in this data consumed from various sources.  
**Outcome**: A new, well-defined list of annotations for operator metadata to define various infrastructure features of an operator.  
**Have you updated the necessary documentation?** NA
=> feat: New infrastructure anotation format to improve the presence of metadata [1.12]

bundle/manifests/gitops-operator.clusterserviceversion.yaml, config/manifests/bases/gitops-operator.clusterserviceversion.yaml
> /kind chore
Add the mandatory annotations of OLM for better visibility.
=> feat: Add mandatory annotations

go.mod, go.sum
=> fix: upgrade argocd-operator-0.9

bundle/manifests/argoproj.io_notificationsconfigurations.yaml, bundle/manifests/gitops-operator.clusterserviceversion.yaml, config/crd/bases/argoproj.io_notificationsconfigurations.yaml, config/manifests/bases/gitops-operator.clusterserviceversion.yaml, go.mod, go.sum
> /kind bug
- Updates the argocd operator version to latest
- fixes issues with notifications controller does not handle context
=> fix: notifications controller does not handle context

bundle/manifests/argoproj.io_rolloutmanagers.yaml, bundle/manifests/gitops-operator.clusterserviceversion.yaml, config/crd/bases/argoproj.io_rolloutmanagers.yaml, config/manifests/bases/gitops-operator.clusterserviceversion.yaml, go.mod, go.sum, scripts/openshiftci-presubmit-all-tests.sh
Update to most recent 'argo-rollouts-manager' commit: https://github.com/argoproj-labs/argo-rollouts-manager/commit/efd9a78591b8be58cd65529dbd624306590911b0
=> Update to latest commit of argo-rollouts-manager 'efd9a78591b8be58cd65529dbd624306590911b0'

go.mod, go.sum
=> fix: upgrade to argo 2.8.18

go.mod, go.sum, test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml
=> fix: upgrade to argo 2.10.9

go.mod, go.sum, test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml
=> fix: upgrade argocd to 2.9.14

bundle/manifests/pipelines.openshift.io_gitopsservices.yaml, go.mod, go.sum, scripts/openshiftci-presubmit-all-tests.sh
Update to most recent 'argo-rollouts-manager' commit: https://github.com/argoproj-labs/argo-rollouts-manager/commit/837f3074a22a072ee7b06dd4e36d7dd8303f92fc
=> Update to latest commit of argo-rollouts-manager '837f3074a22a072ee7b06dd4e36d7dd8303f92fc'

go.mod, go.sum
/kind bug
Include https://github.com/argoproj-labs/argocd-operator/pull/1401 from the argocd-operator
Fixes https://issues.redhat.com/browse/GITOPS-4778
=> Include PR #1401 from argocd-operator

README.md, docs/dex_config_guidance.md
fix small typos in README and dex doc , no change in content
=> doc: fix small typos in README and dex doc

openshift-ci/build-root/Dockerfile
Fixes CI failure
Fixes #?
https://issues.redhat.com/browse/GITOPS-4993
=> Changing registry image to fix CI failure

openshift-ci/build-root/Dockerfile
For enabling OCP 4.16 in CI
Fixes #?
=> Update test image for working with OCP 4.16

bundle/manifests/argoproj.io_rolloutmanagers.yaml, bundle/manifests/gitops-operator.clusterserviceversion.yaml, config/crd/bases/argoproj.io_rolloutmanagers.yaml, go.mod, go.sum, scripts/run-rollouts-e2e-tests.sh
Update to most recent 'argo-rollouts-manager' commit: https://github.com/argoproj-labs/argo-rollouts-manager/commit/a96aa79b546433ee2d68f48d424baaabed0cb2ac
=> Update to latest commit of argo-rollouts-manager 'a96aa79b546433ee2d68f48d424baaabed0cb2ac'

go.mod, go.sum, test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml
=> chore: update argocd to 2.12.3

go.mod, go.sum, test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml
=> chore: update to latest argo

go.mod, go.sum, test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml
/kind cleanup
This PR is updating argocd-operator version.
=> update argocd-operator version

test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml, test/openshift/e2e/parallel/1-066_validate_redis_secure_comm_no_autotls_no_ha/05-check_deployments.yaml, test/openshift/e2e/parallel/1-090_validate_permissions/01-assert.yaml
To fix failing tests in https://github.com/openshift/release/pull/56022
Fixes #?
=> Update tests in v1.12

go.mod, go.sum, test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml
/kind cleanup
This PR update argo-cd and argocd-operator.
=> update argocd-operator version for release 1.13.2

bundle/manifests/argoproj.io_rolloutmanagers.yaml, bundle/manifests/gitops-operator.clusterserviceversion.yaml, config/crd/bases/argoproj.io_rolloutmanagers.yaml, go.mod, go.sum, scripts/run-rollouts-e2e-tests.sh
Update to most recent 'argo-rollouts-manager' commit: https://github.com/argoproj-labs/argo-rollouts-manager/commit/85db81b64541a2e0f10616acca8b24ac63f46b42
=> Update to latest commit of argo-rollouts-manager '85db81b64541a2e0f10616acca8b24ac63f46b42'

bundle/manifests/argoproj.io_applications.yaml, bundle/manifests/gitops-operator.clusterserviceversion.yaml, config/crd/bases/argoproj.io_applications.yaml, go.mod, go.sum, test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml
/kind chore
Upgrade argocd-operator versions
=> chore: Upgrade argocd-operator versions v0.11.2

go.mod, go.sum
Upgrade argo rollout manager
> /kind bug
Fixes #?
=> chore: Upgrade argo rollout manager

.tekton/gitops-operator-pull-request.yaml, .tekton/gitops-operator-push.yaml, Containerfile.plugin
This PR adds separate container image for downstream specific builds. 
Fixes [GITOPS-5882](https://issues.redhat.com/browse/GITOPS-5882)
=> Create downstream container image for konflux

bundle/manifests/argoproj.io_argocds.yaml, bundle/manifests/gitops-operator.clusterserviceversion.yaml, config/crd/bases/argoproj.io_argocds.yaml, go.mod, go.sum
This PR updates argocd-operator for 1.6 release
=> feat: Support multiple ArgoCD instances with ApplicationTrackingAnnotations

OWNERS
- Update OWNERS to reflect current contributors
- Not adding any new names, just removing old.
=> Update OWNERS to reflect current contributors

go.mod, go.sum
/kind bug
Update argocd-operator to include the fix for [GITOPS-6495](https://issues.redhat.com/browse/GITOPS-6495)
Fixes [GITOPS-6495](https://issues.redhat.com/browse/GITOPS-6495)
=> GITOPS-6495 fix for cmp server crashing with busybox image

.tekton/openshift-gitops-operator-bundle-push.yaml
/kind bug
Fix file path in konflux bundle job
Fixes #?
=> ci: Correct path in bundle push job

go.mod, go.sum, test/openshift/e2e/parallel/1-019_validate_volume_mounts/01-assert.yaml, test/openshift/e2e/parallel/1-104_validate_applicationset_tls_scm_volume_mount/01-assert.yaml
* Upgrade to [latest commit from argocd-operator](https://github.com/argoproj-labs/argocd-operator/commit/d8bd8635e78c71413e20bdcfdd2c9fc85dde5407)
* Fix kuttl tests to reflect behaviour changes
* (No CRD/bundle updates needed, I checked)
=> Update to latest commit of argocd-operator

scripts/run-rollouts-e2e-tests.sh
Same as https://github.com/redhat-developer/gitops-operator/pull/881, but for v1.15
=> Backport Subscription update logic for v1.15 Rollouts E2E tests

openshift-ci/build-root/Dockerfile
kind failing-test
Update the image for interoperability tests. Rehearsal jobs are failing as the repo contained non existing image
Fixes #?
=> Update test image in Dockerfile

bundle/manifests/argoproj.io_argocds.yaml, bundle/manifests/gitops-operator.clusterserviceversion.yaml, config/crd/bases/argoproj.io_argocds.yaml, go.mod, go.sum, test/openshift/e2e/parallel/1-083_validate_resource_customization_subkeys/01-assert.yaml
This PR pulls latest argocd-operator and crd, to verify deprecation of initial-repositories and repositoriesCredential fields.
Fixes #GITOPS-6652 
=> update argocd-operator crd and dep 

go.mod, go.sum, test/openshift/e2e/sequential/1-050_validate_sso/07-assert.yaml, test/openshift/e2e/sequential/1-086_validate_default_argocd_role/02-install.yaml
- Update to latest commit from argocd-operator: 5234798de2caa16eb8464808cb8e7dbc8171cd2e
=> Upgrade to latest commit from argo-cd operator '5234798de2caa16eb8464808cb8e7dbc8171cd2e'

controllers/consoleplugin.go, controllers/consoleplugin_test.go
/kind bug
Add a security context to the console plugin deployment so that it complies with the pod security policies.
Fixes https://issues.redhat.com/browse/GITOPS-6777
=> fix: add security context to plugin deployment

controllers/argocd_metrics_controller.go, controllers/argocd_metrics_controller_test.go
/kind bug
fix cve namespace isolation
=> cherrypick fix CVE namespace-isolation break

controllers/consoleplugin.go, controllers/consoleplugin_test.go
/kind bug
Backport https://github.com/redhat-developer/gitops-operator/pull/892 to v1.16
Add a security context to the console plugin deployment so that it complies with the pod security policies.
Fixes https://issues.redhat.com/browse/GITOPS-6777
=> fix(backport): add security context to plugin deployment

go.mod, go.sum
https://github.com/argoproj-labs/argocd-operator/pull/1812 
Fixes #?
=> Fix mount issue with rollouts ui container

controllers/argocd_metrics_controller.go, controllers/consoleplugin.go
Introduce new label on operator managed configmap
Fixes #?
https://issues.redhat.com/browse/GITOPS-7334
=> Introduce new label on operator managed configmap

.ci-operator.yaml, go.mod, go.sum, openshift-ci/build-root/Dockerfile, test/openshift/e2e/ginkgo/parallel/1-031_validate_toolchain_test.go
/kind chore
- Update to latest argocd-operator commit https://github.com/argoproj-labs/argocd-operator/commit/75b2e086ba211654deff43f975d8c2959108b710
=> chore: Update to latest argocd-operator commit '75b2e086ba211654deff43f975d8c2959108b710'

go.mod, go.sum
Downstream securityContext changes
Fixes #?
[GITOPS-7724
](https://issues.redhat.com/browse/GITOPS-7724)
=> Downstream securityContext changes
