redhat-developer/gitops-operator

pkg/controller/gitopsservice/gitopsservice_controller.go

Currently, the route is configured to use TLS termination of type `edge`. This is causing an error when the client is skipping TLS verification
Error:
```
Client sent an HTTP request to an HTTPS server.
``` 
This PR changes the termination type to `reencrypt` , which will make sure the request sent to the backend service is of type `https`

Change TLS termination type to reencrypt

---

README.md
deploy/crds/pipelines.openshift.io_gitopsservices_crd.yaml
deploy/olm-catalog/gitops-operator/manifests/pipelines.openshift.io_gitopsservices_crd.yaml

Currently, the community operators don't support CRD version `apiextensions.k8s.io/v1`. We need to change the version back to `apiextensions.k8s.io/v1beta1` which was the case with earlier versions of `operator-sdk` (<18.0). I updated the CRDs with the following approach:
1. Install `operator-sdk` v0.17.0 locally.
2. Use `operator-sdk generate crds` to update the CRDs
3. Verify if the operator is working as expected
PR to add GItOps operator to OperatorHub: https://github.com/operator-framework/community-operators/pull/2293
Note: I did try to downgrade the `operator-sdk` version. Later inspected the ArgoCD operator and figured out it uses the latest version of `operator-sdk` and the only modified files are CRDs.

Change the CRD version from v1 to v1beta1

---

deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml

PR #9 made changes to the role and role bindings. The roles must also be updated in the CSV file to be applied by the OLM. Should update the CSV in the `community-operators` repo as well.

Update permissions in csv file

---

pkg/controller/gitopsservice/gitopsservice_controller.go
pkg/controller/gitopsservice/gitopsservice_controller_test.go

Users in disconnected clusters rely on mirror registry and manage images using env variables. Read the image for backend service from an env variable to support disconnected environments.

Read images from env variable to support disconnected cluster

---

cmd/manager/main.go
go.mod
go.sum

This PR picks up the latest changes from ArgoCD operator - "Set env var to configure ArgoCD for Cluster Config"
No changes in the manifest files needed.

Pick up latest ArgoCD operator changes for managing cluster resources

---

pkg/controller/argocd/argocd.go
pkg/controller/argocd/argocd_controller.go
pkg/controller/argocd/argocd_controller_test.go
pkg/controller/gitopsservice/gitopsservice_controller.go
pkg/controller/gitopsservice/gitopsservice_controller_test.go
pkg/controller/util/util.go
pkg/controller/util/util_test.go
scripts/run_e2e_tests.sh
test/e2e/gitops_service_test.go

The gitops operator will create an argocd instance with route enabled in `openshift-pipelines-app-delivery`(4.6 cluster) or `openshift-gitops`(4.7 cluster) namespace. The operator must watch for the argocd route in the right namespace based on cluster version.
How to test:
1. Run the operator locally `make run-local`
2. Check for the backend service and argocd instance created in `openshift-pipelines-app-delivery`(4.6 cluster) or `openshift-gitops`(4.7 cluster) namespace.
3. Check if a console link is created
4. Verify e2e tests `make test-e2e`
Breaking Changes/Risk: kam generates argocd resources in argocd namespace. The namespace updates in the operator will not support kam. We need to update kam to generate resources in the right namespace
Note: This PR is pointing to #29

Watch for argocd route in the right namespace

---

go.mod
go.sum

Pick up fix for using red hat redis image arg list which is addressed by  ttps://github.com/argoproj-labs/argocd-operator/pull/238

Pick up fix for using red hat redis image arg list

---

pkg/controller/gitopsservice/kam.go

The current kam image deployed throws an `imagePullBackOff` error. Update the default kam CLI image to use the public quay image

Fix default kam CLI image

---

pkg/controller/argocd/argocd.go
pkg/controller/argocd/argocd_controller.go
pkg/controller/gitopsservice/gitopsservice_controller.go
pkg/controller/gitopsservice/gitopsservice_controller_test.go
test/e2e/gitops_service_test.go

The operator will decide the namespace based on the version of the cluster it is running in.
Expected behavior
4.6 Cluster: Backend service in `openshift-pipelines-app-delivery` and argocd in `openshift-gitops` namespace
4.7 Cluster: Both backend service and argocd in `openshift-gitops` namespace
How to test:
1. Install argocd operator
2. Observe if argocd is installed in `openshift-gitops` namespace
3. If it's a 4.6 cluster, the backend will be deployed in `openshift-pipelines-app-delivery` namespace else it'll get deployed in `openshift-gitops` namespace

Fix Argo CD installation namespace for a 4.6 cluster

---

deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml

This is in accordance to PR https://github.com/argoproj-labs/argocd-operator/pull/238.
GitOps operator by default should use a Red Hat provided redis image.

Use Red Hat provided redis image as default

---

deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml
deploy/role.yaml

Add the permissions to create and manage console download links
```
Reconciler error","controller":"gitopsservice-controller","request":"/cluster","error":"consoleclidownloads.console.openshift.io is forbidden: User \"system:serviceaccount:openshift-operators:gitops-operator\" cannot create resource \"consoleclidownloads\" in API group \"console.openshift.io\" at the cluster scope
```
How to test:
1. Install the operator
2. GitOps application manager link should be present in the list

Add permission to create console download link resource

---

test/e2e/kam_test.go

Fixes:
* Register scheme for ConsoleCLIDownload
* Append `/kam/` to route URL so it matches the CLI download link

Fix e2e test for kam CLI link

---

pkg/controller/argocd/argocd_controller.go

The ConsoleLink Header doesn't make much sense if called "Application Stages" anymore since the ArgoCD instance is also intended to be used for cluster configuration.

Rename "Application Stages" to "OpenShift GitOps"

---

go.mod
go.sum

Picks up the following fixes from upstream ArgoCD Operator - 
- https://github.com/argoproj-labs/argocd-operator/pull/243
- https://github.com/argoproj-labs/argocd-operator/pull/243
Issue:
The issue that this PR addresses is that the operator was creating Role, Role-Binding and Service-Account for Dex even when the service was disabled for OOTB ArgoCD instance. 
Tests: 
Performed manual test by deploying the GitOps Operator with above fixes and verified that specified resources were not created for the OOTB ArgoCD Instance anymore.

pick up upstream fixes for dex reconcile

---

deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml
pkg/controller/add_argocd_metrics.go
pkg/controller/argocdmetrics/argocd_metrics_controller.go
pkg/controller/argocdmetrics/argocd_metrics_controller_test.go
pkg/controller/argocdmetrics/argocdmetrics_controller.go
test/e2e/gitops_service_test.go

Adds a new controller to watch for the creation of ArgoCD instances and to add the configuration to enable the built-in metrics stack to scrape metrics from the new ArgoCD.  Also adds an alert rule to report ArgoCD applications that are out of sync.
Login to an openshift cluster from the command line
Download the operator-sdk binary from here: https://github.com/operator-framework/operator-sdk/releases/tag/v0.17.2
Check out the argocd-metrics branch from https://github.com/jopit/gitops-operator
cd gitops-operator
go mod vendor
kubectl apply -f deploy/crds
operator-sdk run --local --watch-namespace ""
Create a new argocd application in the openshift-gitops namespace with auto-sync turned off, do not sync the app.  It may take several minutes (I've seen it take over five minutes) but …

Add controller to enable metrics/alerts for argocd instances

---

go.mod
go.sum

With PR(https://github.com/argoproj-labs/argocd-operator/pull/247) merged, the operator can now clean up cluster resources on the deletion of the argocd instance.
Fixes #?
1. Login to OpenShift cluster and apply CRDs
```shell
kubectl apply -f deploy/crds
```
1. Run the operator locally
```shell
make run-local
```
2. Create a namespace `test`
3. Create an argocd instance in `test` namespace
4. Delete the instance
5. Observe if the following cluster resources are deleted
Cluster Roles:
* \<cr-name\>-argocd-application-controller
* \<cr-name\>-argocd-server
Cluster …

Update Argo CD operator version

---

deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml

/kind bug
Ensures a specific version of OpenShift Pipelines is installed
Fixes #?
fixes https://issues.redhat.com/browse/GITOPS-675
Steps:
On a 4.7 cluster, Install Pipelines 1.3 using the Preview channel
Install GitOps Operator

Pull in Pipelines v1.3.0 for OCP 4.7

---

go.mod
go.sum

/kind bug
Pull in fix for GITOPS-696 from ArgoCD Operator 
Fixes #?
GITOPS-696
Not tested in this repo but build GitOps Operator TP v1.0.1 candidate to test.
Steps to test:
0. Install GitOps Operator as follow.
1. set DISABLE_DEX=false in the subscription as documented
2. . Do not enable OpenShift authentication in the ArgoCD CR
3.  Create this Job 
```
apiVersion: batch/v1
kind: Job
metadata:
annotations:
argocd.argoproj.io/hook: PostSync
argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
labels:
run: argocd-setup
name: argocd-setup
generateName: argocd-setup-
namespace: …
```

Pull in dex clientID fix from argocd-operator@master

---

Dockerfile
cmd/manager/main.go

{"level":"info","ts":1614286509.002165,"logger":"cmd","msg":"Git Commit: 89b04f64e2774876870de93fbf046b617de2c0cf"}
{"level":"info","ts":1614286509.002208,"logger":"cmd","msg":"Operator Version: 0.0.1"}
{"level":"info","ts":1614286509.0022101,"logger":"cmd","msg":"Go Version: go1.15.5"}
{"level":"info","ts":1614286509.002214,"logger":"cmd","msg":"Go OS/Arch: darwin/amd64"}
{"level":"info","ts":1614286509.0022159,"logger":"cmd","msg":"Version of operator-sdk: v0.18.2"}
{"level":"info","ts":1614286509.0096781,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1614286509.009747,"logger":"leader","msg":"Skipping leader election; not running in a cluster."}

Inject git commit into binary

---

go.mod
go.sum

Pull it fix from argocd-operator https://github.com/argoproj-labs/argocd-operator/pull/248
/kind bug
https://issues.redhat.com/browse/GITOPS-666
Fixes #?
https://issues.redhat.com/browse/GITOPS-666
Not tested in this repo.   The fix will be validated in GitOps 1.0.1 build
Follow the steps in https://github.com/argoproj-labs/argocd-operator/pull/248

Pull it fix from argocd-operator to generate unqiue cluster resource name 

---

deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml

> /kind bug
The GitOps service is a cluster scoped resource that is created by the operator. Since it doesn't have any user input fields, the UI shouldn't expose this resource to the user.
This PR adds an annotation to the operator CSV that makes the resource internal and hides it from OperatorHub UI.
Ref: https://docs.openshift.com/container-platform/4.4/operators/operator_sdk/osdk-generating-csvs.html#osdk-hiding-internal-objects_osdk-generating-csvs
Signed-off-by: Chetan Banavikalmutt <chetanrns1997@gmail.com>
Fixes https://issues.redhat.com/browse/GITOPS-698
1. Install the GitOps operator by building a …

Mark GitOpsService CRD as internal

---

scripts/run_e2e_tests.sh
test/e2e/gitops_service_test.go

Signed-off-by: jannfis <jann@mistrust.net>
This adds tear-down of the `ArgoCD` instance we install during end-to-end testing. Currently, two subsequent runs of end-to-end testsuite on same cluster is not possible, because the `openshift-gitops` namespace won't be correctly deleted - it's stuck in terminating state due to a finalizer on the `ArgoCD` resource which cannot be satisfied, because the operator already is uninstalled when the resource should be deleted. Also, this test is good to have too.
Also, updated the e2e shell script to correctly constraint operator-sdk to pre-v1.0
Fixes #?
**How to test changes / …

Teardown ArgoCD instance in E2E tests

---

go.mod
go.sum

Pick up from argocd operator "Upgraded ArgoCD version from 1.7.7 to 1.8.7 " (#260)
GitOps Operator to support Argo CD 1.8's change in Application Controller Deployment to Replica Sets
https://issues.redhat.com/browse/GITOPS-683
/kind cleanup
Fixes #?
Not tested on this repo.   To be tested on 1.1 build candidates
Steps to test:
1. Upgrade GitOps Operator from 1.0.1 to 1.1.0
2. Verify that argocd application controller is running as replica set in the `openshift-gitops` namespace (oc get …

Pick up from argocd operator "Upgraded ArgoCD version from 1.7.7 to 1.8.7"

---

deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml

This reverts commit 6ce0ddf1dc8880ab006b8a71bb21c977d0d704bb. The 404 error was due to a bug in the GitOps plugin in the UI. It should be fixed in the OpenShift console repo
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1937929
Fixes #?

Revert "Mark GitOpsService CRD as internal (#68)"

---

go.mod
go.sum

Sync upstream argocd operator to pickup
https://github.com/argoproj-labs/argocd-operator/pull/266 support compliance.openshift.io apiGroup for cluster config
https://github.com/argoproj-labs/argocd-operator/pull/265 OpenShift hooks for HA
https://github.com/argoproj-labs/argocd-operator/pull/267 support compliance.openshift.io apiGroup for cluster config
Fixes #?
No testing done on this repo.  To be tested on v1.1.0 build.
https://github.com/argoproj-labs/argocd-operator/pull/265 OpenShift hooks for HA
https://github.com/argoproj-labs/argocd-operator/pull/267 …

Sync argocd operator master

---

Makefile

Signed-off-by: jannfis <jann@mistrust.net>
The `run-local` target of the Makefile uses a hard-coded binary name of `operator-sdk`. This PR lets user override the name of the binary to use by setting the `OPERATOR_SDK` environment variable, so that a version/binary can be used.
Fixes #?

Let user override operator-sdk binary for run-local target of Makefile

---

Dockerfile
build/redis/haproxy.cfg.tpl
build/redis/haproxy_init.sh.tpl
build/redis/init.sh.tpl
build/redis/redis.conf.tpl
build/redis/sentinel.conf.tpl

> /kind bug
Adds the configuration files for Redis HA mode to the operator's image.  Otherwise the redis-ha-server and redis-ha-haproxy pods fail to start.
Fixes #?
Install an ArgoCD instance in HA mode.  If all the pods start, it's workiing.

Add Redis HA config files to operator image

---

go.mod
go.sum

Pickup upstream fixes: 
* Upgrade argo-cd from v1.8.7 to v2.0-rc1 #270
* fix: add repository credentials from CR to the existing argocd config… #269
> /kind bug
Fixes #?
See "how to test" instructions in PRs:
https://github.com/argoproj-labs/argocd-operator/pull/269
https://github.com/argoproj-labs/argocd-operator/pull/270

Pickup upstream fixes

---

pkg/controller/gitopsservice/gitopsservice_controller.go
pkg/controller/gitopsservice/gitopsservice_controller_test.go

This PR creates a Cluster Role and Cluster Role Binding which provides the permissions to list/get/watch Application object in argoproj.io api and associate it with the Service Account for Gitops Backend Service (cluster). 
Creates SA/Cluster_Role/Cluster_Role_Binding with the name : "gitops-backend-service-cluster"
TODO: 
Fixes #?
- Deploy the latest GitOps operator with these changes.
- Check deployement yaml for GitOps Backend Service, it should have a `serviceAccount/serviceAccountName = gitops-backend-service-cluster`
- Check if …

add service account with required permissions for backend service

---

go.mod
go.sum
pkg/controller/gitopsservice/gitopsservice_controller.go
pkg/controller/gitopsservice/gitopsservice_controller_test.go
pkg/controller/gitopsservice/kam.go

- Sets compute resources for the kam and backend pods.
- Sets resource quotas for the *openshift-gitops* namespace
GITOPS-890
Install the operator.  The *openshift-gitops* namespace should have resource quotas set, and all argocd pods in that namespace should start successfully.
**Note to Reviewers** The resource quotas for the namespace were calculated by adding up all the compute resources for the various workloads and then multiplying the total by 1.5.

Set default namespace resource quotas

---

deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml

> /kind bug
With new changes introduced in the Operator, it needs the permissions to list/watch/create `ResourceQuotas`. These permissions are needed to be added to the `gitops-operator` service account.  
Fixes #?
REPRODUCING THE ISSUE:
- Build a custom gitops operator bundle with the latest changes. 
- Deploy the Gitops Operator using the bundle, it would fail to create the default ArgoCD instance in openshift-gitops namespace as it doesn't have the permissions to create Resource Quotas.
TESTING THE FIX:
- Create a custom bundle with these changes. …

added permissions to create resource quotas for gitops-operator

---

test/e2e/gitops_service_test.go
test/e2e/rhsso_test.go

Adds e2e tests for RHSSO Installation and Configuration. This mere purpose of this PR is to verify e2e scenarios for PR - https://github.com/redhat-developer/gitops-operator/pull/124
Test Scenarios covered by this PR:
1. Verify RHSSO installation for default instance.
2. Verify RHSSO Configuration.
3. Verify RHSSO Uninstallation.
4. ReInstall RHSSO
NA
Adds e2e tests for https://github.com/redhat-developer/gitops-operator/pull/124
Download the PR and run `make test-e2e`

Add e2e tests to verify RHSSO Configuration

---

Makefile
test/e2e/gitops_service_test.go

Running the e2e test on the operator which is already installed in the cluster. It will be helpful for running e2e test on downstream staging operator images. Also the same make target can be used for freshly compiled and installed upstream gitops operator image 
Fixes NA
1. Install gitops operator
2. run `make test-e2e-on-operator`

Make target for running e2e test on installed operator

---

scripts/run_e2e_tests.sh

/kind bug
https://github.com/redhat-developer/gitops-operator/issues/133
Fixes #133

Exit on test failure

---

test/e2e/gitops_service_test.go

> /kind bug
This PR adds a simple E2E test for creation of cluster-scoped ArgoCD instance in a new namespace.
N/A
Fixes #?
N/A

Add E2E test for cluster-scoped namespace

---

scripts/run_e2e_tests.sh
test/e2e/gitops_service_test.go
test/helper/application_status.go

ApplicationHealthStatus and ApplicationSyncStatus are assuming that an empty health/sync string means it is healthy/synced.
These functions should only return nil if the application is Healty and Synced, respectively.
Also:
- Using a slightly more efficient jsonpath query
- `cmd.Stdout = &stdout` should be before `cmd.Run()`
- Added `export ARGOCD_CLUSTER_CONFIG_NAMESPACES=openshift-gitops` to mimic the environment of the OLM-based install
- Removed another of the `time.Sleep`s
- The `validateMachineConfigUpdates` test is failing due to https://github.com/redhat-developer/gitops-operator/issues/148 (it previously appeared to pass in the test framework, but that was because ApplicationHealthStatus was not properly checking the health)
-  So I …

ApplicationHealthStatus and ApplicationSyncStatus are assuming that an empty health/sync string means it is healthy/synced

---

go.mod
go.sum

> /kind bug
Updates go.mod to point to the latest upstream operator commit to include updated e2e-tests and permissions by namespace labelling
Fixes #?

chore: update go.mod to point to latest upstream commit  

---

deploy/crds/argoproj.io_argocds_crd.yaml
go.mod
go.sum

Add RHSSO support for OpenShift Disconnected Cluster
This PR adds RHSSO support for OpenShift Disconnected cluster.
Documentation is updated in the upstream docs. Similar documentation will be published to OpenShift Docs.
https://argocd-operator.readthedocs.io/en/latest/usage/keycloak/#additional-steps-for-disconnected-openshift-clusters
1. Create a operator bundle and an Index Image.
2. Deploy the Index Image in Disconnected cluster.
3. Verify keycloak pods are running in openshift-gitops namespace.
4. On the Argo CD UI page, You should see an option to Login with Keycloak

feat: Add RHSSO support for OpenShift Disconnected Cluster

---

Makefile
common/common.go
pkg/controller/gitopsservice/gitopsservice_controller.go
pkg/controller/gitopsservice/gitopsservice_controller_test.go
scripts/run_e2e_tests.sh
test/e2e/gitops_service_test.go
test/helper/application_status.go
test/nondefaulte2e/gitops_service_nondefault_test.go
test/nondefaulte2e/main_test.go

This PR:
- Adds a `DISABLE_DEFAULT_ARGOCD_INSTANCE` environment variable to the GitopsService reconciler, which, if true, will prevent an ArgoCD instance from being create in the `openshift-gitops` namespace.
- If this environment variable is set, the `openshift-gitops` still is created, as are the `cluster` and `kam` resources
- If this environment variable is set, any existing `ArgoCD` instances in `openshift-gitops` namespace will be deleted.
- Unit test to verify the above works as expected
- E2E tests to verify the above works as expected
- But since the operator needs to run with the above environment variable set, I created a new e2e test dir for these tests
- Tests under `test/nondefaulte2e` …

Add DISABLE_DEFAULT_ARGOCD_INSTANCE environment variable to operator to disable creation of default Argo CD instance

---

deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml
pkg/controller/argocd/argocd.go
pkg/controller/argocd/argocd_test.go
test/e2e/gitops_service_test.go
test/e2e/rhsso_test.go

Do not install RHSSO OOTB for default Argo CD instance. This PR merely removes the code that installs RHSSO OOTB for default Argo CD instance.
Internal docs updated, This document will be used as reference to update the OpenShift Docs.
https://docs.google.com/document/d/1vyWQIumR8dFAKf_DNuNkLXdMP4pgLLM2nEpe_CPSyXI/edit?ts=60d9c4c2#
#159
Fixes #?
#159
1. Run the operator locally using `operator-sdk run local`
2. Run `oc get pods -n openshift-gitops` to ensure that no Keycloak pods are deployed.

feat: Do not install RHSSO OOTB for default Argo CD instance

---

test/appcrs/nginx_default_ns_appcr.yaml
test/e2e/gitops_service_test.go

> /kind bug
adds an e2e test case to validate permissions by label for ootb argocd instance and a new target namespace 
Fixes [GITOPS-1004](https://issues.redhat.com/browse/GITOPS-1004)?

add e2e test to validate permissions by label for OOTB argocd instance

---

deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml

/kind bug
Only the ArgoCD CRD should be displayed as an operator-backed item in the developer catalog in Dev Console.
https://issues.redhat.com/browse/GITOPS-933 
Fixes #? 
1. Create a custom index image by following instruction in https://github.com/redhat-developer/gitops-operator#re-build-and-deploy
2. Make custom operator available in the operator hub https://github.com/redhat-developer/gitops-operator#making-the-operator-available-on-the-in-cluster-operatorhub 
3. Install the custom operator
4. Upon successful installation, check the developer …

bug: remove additional operator-backed items in the developer catalog

---

pkg/controller/argocd/argocd.go
pkg/controller/argocd/argocd_test.go

Signed-off-by: jannfis <jann@mistrust.net>
/kind bug
Set the default resource requests to a more sane value to allow scheduling on small and/or loaded clusters. Defaults can still be overriden by the user.
Fixes #? https://issues.redhat.com/browse/GITOPS-1171
* Create new ArgoCD CR instance
* Check created resources (deployment of argocd-repo-server and application set controller as well as statefulset of application controller) for having CPU requests set to 250m

fix: Lower default CPU resource requests for better scheduling

---

scripts/run_e2e_tests.sh
test/e2e/gitops_service_test.go
test/helper/application_status.go
test/nondefaulte2e/gitops_service_nondefault_test.go

/kind cleanup
Improve the helper namespace deletion logic I added in a previous PR
It is possible for the `openshift-gitops` namespace to still have an active `ArgoCD` instance, at the end of the previous E2E test, which blocks deletion of the `openshift-gitops` namespace (due to the ArgoCD finalizer). 
Which looks like this:
```
I0709 12:50:50.199629   10291 request.go:621] Throttling request took 1.13356149s, request: GET:https://api.ci-op-dpljqn95-02c74.origin-ci-int-aws.dev.rhcloud.com:6443/apis/build.openshift.io/v1?timeout=32s
I0709 12:51:00.397791   10291 request.go:621] Throttling request took 11.331586527s, request: GET:https://api.ci-op-dpljqn95-02c74.origin-ci-int-aws.dev.rhcloud.com:6443/apis/coordination.k …
```

Improve helper namespace deletion

---

deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml
pkg/controller/argocd/argocd.go
pkg/controller/argocd/argocd_test.go

> /kind bug
Argo CD installation from operator console fails as HA.Enabled is not set by default
NA
Created a new Catalog Source to test this changes.
```
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
name: gitops-service-source-av
namespace: openshift-marketplace
spec:
displayName: 'Gitops Service by Red Hat'
image: 'quay.io/aveerama/gitops-backend-operator-index:v0.0.4'
publisher: 'Red Hat Developer'
sourceType: grpc
```

fix: Argo CD installation from operator console fails as HA.Enabled is not set by default

---

deploy/crds/argoproj.io_argocds_crd.yaml
deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml
go.mod
go.sum

* https://github.com/argoproj-labs/argocd-operator/pull/362  feat: Add the ability to specify additional kustomize versions within the ArgoCD ConfigMap #362
* https://github.com/argoproj-labs/argocd-operator/pull/366  fix: Allow ArgoCD CR to override keycloak resource request/limit defaults #366
/kind bug
Fixes #?
Please refer to …

Pull in fixes from argocd operator:  #362, #366

---

deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml

Signed-off-by: jannfis <jann@mistrust.net>
/kind bug
PR #167 set lower default resource limits for the workloads installed through an ArgoCD CR. When created by DevConsole, default values are taken from the CSV, so those instances are using the old defaults. This change aligns the values.
Fixes #?
* Create `ArgoCD` instance via DevConsole
* Take a look at resource requests for application controller and repo server workloads

fix: Align default resource limits with instances created in DevConsole

---

test/e2e/rhsso_test.go

> /kind bug
fix: Updated RHSSO failing tests for make target "test-e2e-on-operator"
```
rhsso_test.go:57: no kind is registered for the type v1.ClusterVersion in scheme "github.com/operator-framework/operator-sdk/pkg/test/framework.go:130"
```
NA
* [] Unit Test
Run the operator either locally or using operator hub.
Patch the Argo CD CR to enable Login with Keycloak.
```
spec:
sso:
provider: keycloak
```
Wait for the operator to reconcile keycloak changes. RHSSO may take a couple of minutes to start.
Run the make target `make test-e2e-on-operator` and note that you dont see the below …

fix: Updated RHSSO failing tests for make target "test-e2e-on-operator"

---

go.mod
go.sum

> /kind bug
Pull in #372 from argocd-operator
I have observed an unexpected crash of the operator when the operator is trying to reconcile an empty Argo CD configmap.
I can reproduce this issue by creating an empty Argo CD configmap (argocd-cm) in a namespace and then creating an Argo CD CR. Noticed that operator crashed while reconciling the empty configmap.
Error:
```
goroutine 1873 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1769d40, 0x1b43340)
/remote-source/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.18.3/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/remote-source/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.18.3/pkg/util/runtime/runtime.go:48 …
```

fix: Pull in #372 from argocd-operator

---

go.mod
go.sum
pkg/controller/gitopsservice/gitopsservice_controller.go
pkg/controller/gitopsservice/gitopsservice_controller_test.go
pkg/controller/gitopsservice/kam.go

> /kind bug
This PR addresses the following issue.
After upgrading to v1.2, Resource Quota has been configured in `openshift-gitops` namespace by the operator.   However, existing Deployments do not contain Resource limit/request.   When any one of the existing pods are deleted, new pods failed to start because resource limit/requests are not defined in the Deployments.`
This PR makes the following changes:
* When reconciling the default instance, we make sure the following workloads contain resource request/limit definitions.
** applicationset controller
** application controller
** dex
** grafana
** ha proxy
** redis
** repo server
* Reconcile resource …

fix: set resource requirements to containers incase of the operator upgrade

---

bundle/manifests/gitops-operator.clusterserviceversion.yaml
config/manager/manager.yaml
test/e2e/gitopsservice_test.go
test/e2e/suite_test.go
test/nondefaulte2e/suite_test.go

This PR set the DISABLE_DEX environment variable to true in CSV.  By doing so, the Dex workload is enabled and the operator controller reconciler dex/oidc configuration.
run the operator locally using `operator-sdk run local`
After a couple of minutes, verify the install installation is successful and pod is up and running.

feat: Set the DISABLE_DEX environment variable to true in CSV

---

bundle/manifests/gitops-operator.clusterserviceversion.yaml
config/samples/argoproj.io_v1alpha1_argocd.yaml
controllers/argocd/argocd.go
controllers/argocd/argocd_test.go

#190 installs the dex service out of the box. This PR would additionally configure `OpenShift Login` as a default. 
This PR would allow users to login to the Argo CD using their OpenShift users without any manual intervention or additional steps. This PR also sets the users which belong to `system:cluster-admins` as Argo CD admins. For example, `kubeadmin` user belongs to the `system:cluster-admins` group, which allows users/admins to login using the `kubeadmin` and perform admin activities.
NA
Documentation:
https://github.com/argoproj-labs/argocd-operator/pull/418
**Test acceptance …

feat: Configure OpenShift Login for Dex OOTB

---

controllers/argocd/argocd.go
controllers/argocd/argocd_test.go
controllers/gitopsservice_controller.go
controllers/gitopsservice_controller_test.go

> /kind bug
Documentation is updated as part of the PR https://github.com/argoproj-labs/argocd-operator/pull/412
#206 #207 #208 
Fixes #?
#206 #207 #208 
1. run the operator locally using `operator-sdk run local`
2. verify that there is no resource quota on the `openshift-gitops` namespace.
3. verify that the repo server memory limit is increased from `512Mi` to `1024Mi`
4. verify that a well explained documentation is available for managing resource requirements of Argo CD workloads.

fix: issues with resource quota and resource requirements

---

bundle.Dockerfile
bundle/manifests/gitops-operator.clusterserviceversion.yaml
bundle/manifests/gitops-operator_v1_serviceaccount.yaml
bundle/metadata/annotations.yaml
bundle/tests/scorecard/config.yaml

There's been a change in the operator-sdk version 1.10.1 to not generate a file (bundle/manifests/gitops-operator_v1_serviceaccount.yaml) when running make bundle, and in version 1.11.0 the presence of that file will actually cause make bundle to error out. This PR is to remove that file and regenerate the bundle artifacts using operator-sdk version 1.11.0
Install v1.11.0 version of operator-sdk
run `make bundle`. You should not run into any issues.

chore: update operator-sdk to v1.11.0

---

bundle/manifests/gitops-operator.clusterserviceversion.yaml
config/samples/argoproj.io_v1alpha1_argocd.yaml

The PR #205 missed to update the repo server resource limit in the argo cd sample. This PR addresses the issue.
NA
This PR completes the PR #205 
1. Use the steps provided in the README.md to create an index image.
https://github.com/redhat-developer/gitops-operator#re-build-and-deploy
2. Install the new operator from OperatorHub
3. Go to the project of your choice and move to `Installed Operators` section in the console.
4. Click on `Red Hat OpenShift GitOps`.
5. …

chore: update repo server resource limit in argocd sample

---

deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml
pkg/controller/argocd/argocd.go
pkg/controller/argocd/argocd_test.go
pkg/controller/gitopsservice/gitopsservice_controller.go
pkg/controller/gitopsservice/gitopsservice_controller_test.go

> /kind bug
Documentation is updated as part of the PR https://github.com/argoproj-labs/argocd-operator/pull/412
* Remove resource quota in the namespace openshift-gitops in the controller reconciler.  When the operator is upgraded, existing resource quota is removed.
* Increase the default memory limit to 1024M in the repo server.  It only affects new installation.  Existing derault argocd instance workload is not affected.
Fixes #?
#206 #207 #208 
1. run the operator locally using `operator-sdk run local`
2. …

fix: issues with resource quota and resource requirements (v1.2.1)

---

bundle/manifests/argoproj.io_argocds.yaml
config/crd/bases/argoproj.io_argocds.yaml

Support Application Controller Sharding. This PR pulls the latest PR 384 from the upstream argocd-operator.
[384](https://github.com/argoproj-labs/argocd-operator/pull/384) -> Add ability to shard application controller.
NA
run gitops-operator locally using `operator-sdk run local`
create a basic argocd resource as below
apiVersion: argoproj.io/v1alpha1
```
kind: ArgoCD
metadata:
name: example-argocd
labels:
example: basic
spec:
controller:
sharding:
enabled: true
replicas: 3
```
Verify the provider replicas of application controller are created and a new environment variable with name …

feat: Support application controller sharding, pull #384 from argocd-operator

---

controllers/gitopsservice_controller.go
controllers/gitopsservice_controller_test.go

> /kind bug
A part[1] of PR #205 removes the logic to add resource limits to workloads during operator upgrade. This needs to reverted as we just want to delete the resource quota on the openshift-gitops(default) namespace and not change any of the existing behavior w.r.t resource limits.
1 - https://github.com/redhat-developer/gitops-operator/pull/205/files#r708223171
NA
1. Upgrade the operator from v1.1.2 or less to v1.3
2. All the ArgoCD workloads should be set with resource requests/limits.

chore: Restore logic to add resource limits to workloads incase of operator upgrades.

---

go.mod
go.sum

> /kind bug
Points gitops-operator to the latest commit of argocd-operator which makes it OCP 4.9 compatible
Fixes #?

update argocd-operator to latest commit

---

deploy/argocd_role.yaml
deploy/olm-catalog/gitops-operator/manifests/gitops-operator.clusterserviceversion.yaml

> /kind bug
This PR adds permissions to the operator pod to delete the resourcequota objects.
NA
1. Upgrade the operator from v1.2 to v1.2.1 and see that the resourcequota on openshift-gitops namespace is not deleted.
After this change it should be deleted.

fix: Add permissions to the operator to delete resourcequotas.

---

Makefile

> /kind bug
The default timeout for `go test` is 10 mins which may lead to timeout and result in test suite failure. 
```
-timeout d
If a test binary runs longer than duration d, panic.
If d is 0, the timeout is disabled.
The default is 10 minutes (10m).
```
NA
Fixes #?
#228 
NA

chore: Increase the default timeout for e2e tests

---

bundle/manifests/gitops-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/gitopsservice_controller.go

> /kind bug
This PR ports the changes #223 into master branch.
NA
Upgrade the operator from v1.2 to v1.3 and see that the resourcequota on openshift-gitops namespace is not deleted.
After this change it should be deleted.

fix: Add permissions to operator to delete ResourceQuota object on namespace

---

controllers/gitopsservice_controller.go

Before the operator sdk upgrade, only some of the watches set by the
gitops service controller included a predicate.  After the upgrade,
all of the watches use the predicate.  This causes some user-made
changes to resources like the cluster role not to be reverted
by the operator.
This fix removes the predicate from the watches which didn't have it
before.  It also adds the predicate to the primary resource, which did
have it before the upgrade, but was missing after.
> /kind bug
Fixes a regression where user changes to the cluster roles would not be reverted by the operator
Fixes #? …

fix: remove predicate from some watches

---

README.md

Current readme uses `redhat-developer` for creating and pushing docker image. As most users don't have access to redhat-developer quay account, it is better to add placeholder so that they can run the commands using their quay account.

doc: readme fix for quay username placeholder

---

controllers/argocd/argocd.go
controllers/argocd/argocd_test.go

Signed-off-by: Yi Cai yicai@redhat.com
Report from a user:
> Currently the following policy.csv is set to "g, system:cluster-admins, role:admin". This means when a cluster admin logs into openshift gitops via Dex/SSO they can't really do anything useful, and the errors when they do something like a Sync aren't obvious. A less astute openshift user wouldn't even realize that system:cluster-admin and cluster-admin are different groups. We should include cluster-admin as well as system:cluster-admin. 
This is achievable with the following patch
oc patch argocd openshift-gitops -n openshift-gitops --type=merge …

fix: add cluster-admins to defualt argocd rbac policy

---

go.mod
go.sum

fixes #271 
Fixes #271 
-------------------------
1. Run the operator locally using `make install run`
2. Create an Argo CD Instance or use the default Argo CD instance.
3. Add a cert to argocd-tls-certs-cm configmap.
```
..........
data:
test.example.com: '-----BEGIN CERTIFICATE-----  -----END CERTIFICATE-----'
```
4. operator SHOULD NOT remove the configmap changes added manually in step 3.

fix: argocd-tls-certs-cm gets overwritten by the operator

---

go.mod
go.sum

pulls https://github.com/argoproj-labs/argocd-operator/pull/555
**This PR adds the below enhancements.**
-------------------------------------------
* Upgrades the default version of RH-SSO to 7.5.1
* Adds support to login with `kube:admin` OpenShift User.
* With this PR, RH-SSO can fetch the group details of OpenShift Users(You should see the group details of the logged in user in the Argo CD console). This will help admins define Group Level RBAC for their OpenShift groups. 
https://github.com/keycloak/keycloak/pull/8381
* Kube:admin by default you only have. Not working previously. not an OS user.
https://github.com/keycloak/keycloak/pull/8428
* RHSSO works in proxy enabled cluster with no …

feat: pull argoproj-labs/argocd-operator#555 (RH-SSO enhancements)

---

bundle/manifests/argoproj.io_argocds.yaml
bundle/manifests/gitops-operator.clusterserviceversion.yaml
config/crd/bases/argoproj.io_argocds.yaml
config/samples/argoproj.io_v1alpha1_argocd.yaml
controllers/argocd/argocd.go
controllers/argocd/argocd_test.go
controllers/gitopsservice_controller.go
controllers/gitopsservice_controller_test.go
go.mod
go.sum
test/e2e/gitopsservice_test.go

> /kind bug
This PR contains the changes required to enable gitops-operator to consume the SSO unification changes that will go into argocd-operator
It ensures the default instance is populated with `.spec.sso.provider=dex` instead of `.spec.dex` out of the box 
and also adjusts the reconciliation logic for the same 
It updates the Argo CD CR to contain the new SSO fields 
Fixes #?
**How …

feat: Unify SSO configuration under `.spec.sso` in backward compatible way

---

go.mod
go.sum

/kind cleanup
Updates to the latest argocd-operator (release-0.4) branch

chore: update to latest argocd-operator

---

go.mod
go.sum

> /kind bug
Redis Image upgrade is not work as expected. There is an issue with the current implementation that does not allow the operator to upgrade the redis image.
This PR will fix the above issue.
NA
1. Run the below UnitTest
`/usr/local/go/bin/go test -timeout 30s -run ^TestReconcileArgoCD_reconcileRedisDeployment_testImageUpgrade$ github.com/argoproj-labs/argocd-operator/controllers/argocd`
or
2. Run the operator locally using `make install run`
- Create an Argo CD instance.
- Stop the operator
- Rerun the operator using the below command …

fix: issues with redis upgrade

---

controllers/argocd/openshift/openshift.go
controllers/argocd/openshift/openshift_test.go

/kind bug
The OpenShift version of the haproxy image sets the `net_bind_service` capability on the haproxy binary.  The haproxy deployment needs to configure this capability in the security context in order to allow the binary to run.
Fixes #?
Run the operator with the OpenShift images
```bash
ARGOCD_REDIS_IMAGE=registry.redhat.io/rhel8/redis-6@sha256:7d4cb67a6416cb43d4b84663e9ede302f25df149febec132134dea5302c7c692 \
ARGOCD_REDIS_HA_IMAGE=registry.redhat.io/rhel8/redis-6@sha256:7d4cb67a6416cb43d4b84663e9ede302f25df149febec132134dea5302c7c692 \ …
```

Fix openshift haproxy crash (1.6)

---

go.mod
go.sum

> /kind bug
Update to the latest argocd-operator, which pulls in argocd version 2.4.5
Fixes #?

Update argocd to 2.4.5

---

go.mod
go.sum

> /kind bug
Pulls in the latest release 0.4 of the argocd-operator, which updates argocd to 2.4.6
Fixes #?

Update to argocd 2.4.6

---

common/common.go
controllers/argocd_controller.go
controllers/argocd_controller_test.go
docs/OpenShift GitOps Usage Guide.md

For users in multi-tenant clusters, there can be multiple instances of Argo CD. This means that if a user installs Argo CD in their own namespace, the link that is displayed in the application launcher would be for a different instance of Argo CD, which is confusing. Before there was no way to permanently delete the Argo CD consoleLink, since it would be created again when the ArgoCDRoute was reconciled. 
This PR adds a new environment variable, `DISABLE_DEFAULT_ARGOCD_CONSOLELINK` that shows the following behavior: 
- when `DISABLE_DEFAULT_ARGOCD_CONSOLELINK=true`, the consoleLink will be permanently deleted. 
- when `DISABLE_DEFAULT_ARGOCD_CONSOLELINK=false` **or not set (default)**, the …

feat: implement ability to disable default argocd consoleLink

---

bundle/manifests/gitops-operator-controller-manager-metrics-service_v1_service.yaml
bundle/manifests/gitops-operator.clusterserviceversion.yaml
config/manager/manager.yaml
config/prometheus/monitor.yaml
config/rbac/auth_proxy_service.yaml
test/e2e/gitopsservice_test.go

> /kind bug
operator-sdk sets the default labels as `control-plane: controller-manager` in the manifests. This label is generic and should be modified according the operator.
One of the users has reported the below [issue](https://coreos.slack.com/archives/CMP95ST2N/p1658320079802799) on coreos slack.
```
I have a customer on ROSA on 4.9.37 who have got these operators installed from the OperatorHub.
Red Hat OpenShift GitOps  -----> 1.5.4 provided by Red Hat Inc.
GitLab Runner ----> 1.9.0 provided by GitLab, Inc.
The target namespace for these operators in "openshift-operators" and cannot be overridden.
The GitLab runner installs  3 services with a pod selector "control-plane=controller-manager".
This pod selector …
```

fix: operator resource labels should be unique

---

controllers/argocd_controller.go
controllers/argocd_controller_test.go
controllers/kam.go
controllers/util/util.go
main.go
test/e2e/suite_test.go
test/nondefaulte2e/suite_test.go

Support console api being optional
> /kind bug
Fixes #?

Support console api being optional

---

common/common.go
controllers/gitopsservice_controller.go
controllers/gitopsservice_controller_test.go
go.mod
go.sum

To avoid multiple "Environments" button showing up in left menu on Developer tab in DevConsole.
Fixes GITOPS-2415
1. On OCP 4.15 or greater, observe that Console Plugin section is showing up on GitOps-operator installation page. Only one "Environments" button exists on Developer tab left menu.
2. On OCP 4.14 or lower, observe that Console Plugin section is not showing up on GitOps-operator installation page. Only one "Environments" button exists on Developer tab left menu.

Add reconcile plugin condition

---

bundle/metadata/annotations.yaml

> /kind bug
Updates the bundle package name to `openshift-gitops-operator` from `gitops-operator` to fix the failing operator bundle tests.

fix: update the bundle package name to openshift-gitops-operator

---

bundle/manifests/gitops-operator.clusterserviceversion.yaml

> /kind bug
When I tried to build a bundle out of this branch and deploy into the openshift platform, I noticed that we have many unwanted arguments that brings operator container into `crashLoopBackOff`
This PR removes all those unwanted arguments
```
lag provided but not defined: -secure-listen-address
Usage of /usr/local/bin/manager:
-health-probe-bind-address string
The address the probe endpoint binds to. (default ":8081")
-kubeconfig string
Paths to a kubeconfig. Only required if out-of-cluster.
-leader-elect
Enable leader election for controller manager. Enabling this will ensure there is only one active controller manager.
-metrics-bind-address …
```

fix: remove unwanted arguments from the operator container

---

bundle/manifests/gitops-operator.clusterserviceversion.yaml
config/manifests/bases/gitops-operator.clusterserviceversion.yaml
test/openshift/e2e/parallel/1-038_validate_productized_images/02-check-images.yaml
test/openshift/e2e/parallel/1-090_validate_permissions/01-assert.yaml
test/openshift/e2e/sequential/1-018_validate_disable_default_instance/04-assert.yaml
test/openshift/e2e/sequential/1-031_validate_toolchain/01-check.yaml
test/openshift/e2e/sequential/1-077_validate_workload_status_monitoring_alert/02-verify-alert.yaml
test/openshift/e2e/sequential/1-085_validate_dynamic_plugin_installation/02-install-dynamic-plugin.yaml

Signed-off-by: varshab1210 <vab@redhat.com>
Modifying Kuttl tests to be compatible with Openshift CI checks
Fixes #?
CI checks would fail because it is installing the released version of operator instead of building operator from PR changes.
I have raised a PR addressing this issue https://github.com/openshift/release/pull/35922 but in order for its CI checks to pass this PR needs to be merged and [this](https://issues.redhat.com/browse/GITOPS-2641) issue needs to be fixed. Also there are some 1.8.0 RC bugs that needs to be …

Fix failing Kuttl tests

---

test/openshift/e2e/parallel/1-090_validate_permissions/01-assert.yaml
test/openshift/e2e/sequential/1-077_validate_workload_status_monitoring_alert/02-verify-alert.yaml

Modifying incorrect CSV name
Fixes #?

Correcting CSV name in 1-090_validate_permissions

---

test/openshift/e2e/sequential/1-077_validate_workload_status_monitoring_alert/01-assert.yaml
test/openshift/e2e/sequential/1-077_validate_workload_status_monitoring_alert/01-install.yaml
test/openshift/e2e/sequential/1-077_validate_workload_status_monitoring_alert/02-verify-alert.yaml

Commenting https://github.com/redhat-developer/gitops-operator/tree/master/test/openshift/e2e/sequential/1-077_validate_workload_status_monitoring_alert test as it is failing continuously in Openshift CI and blocking the merge of https://github.com/openshift/release/pull/35922. Will re-enable once https://issues.redhat.com/browse/GITOPS-2664 is fixed
Fixes #?

Disabling workload-status-monitoring test

---

bundle/manifests/gitops-operator.clusterserviceversion.yaml
go.mod
go.sum

Pulls the latest from argocd-operator (which upgrades argocd version to 2.6.3)
(https://github.com/argoproj-labs/argocd-operator/commit/cdcfcb7a6653a6d65fb780f8da2b8d26af8ca4fb)

update latest argocd-operator version

---

controllers/gitopsservice_controller.go
controllers/gitopsservice_controller_test.go
controllers/kam.go
controllers/util/util.go

/kind bug
port changes from #451 into v1.8 release branch
Fixes #?

fix: add security context for kam and cluster pods

---

Makefile
README.md
bundle/manifests/gitops-operator.clusterserviceversion.yaml
bundle/metadata/annotations.yaml
config/manager/kustomization.yaml
config/manifests/bases/gitops-operator.clusterserviceversion.yaml
scripts/openshiftci-olm-kuttl-tests.sh

This PR renames gitops-backend-operator to gitops-operator and changes env variable VERSION to avoid dependency with Openshift CI. Setting VERSION to an empty string would set the image tag to "latest" by default 
Fixes #?

Changing naming conventions

---

controllers/gitopsservice_controller.go
controllers/kam.go

> /kind bug
KAM security context was added as part of #451 which is working fine for `v1.8.0 release candidate` installation but fails when user tries to update from `1.7.2` to `1.8 release candidate`.
NA
Fixes https://issues.redhat.com/browse/GITOPS-2729
- Create the `v1.8.0-rc` by using the below steps.
```
make docker-build IMG=quay.io/aveerama/gitops-backend-operator:1.8.0-rc
make docker-push IMG=quay.io/aveerama/gitops-backend-operator:1.8.0-rc
rm -fr bundle
make bundle IMG=quay.io/aveerama/gitops-backend-operator:1.8.0-rc
make bundle-build …
```

fix: handle kam security context during upgrades

---

controllers/gitopsservice_controller.go
controllers/kam.go

> /kind bug
KAM security context was added as part of #451 which is working fine for `v1.8.0 release candidate` installation but fails when user tries to update from `1.7.2` to `1.8 release candidate`.
NA
Fixes https://issues.redhat.com/browse/GITOPS-2729
- Create the `v1.8.0-rc` by using the below steps.
```
make docker-build IMG=quay.io/aveerama/gitops-backend-operator:1.8.0-rc
make docker-push IMG=quay.io/aveerama/gitops-backend-operator:1.8.0-rc
rm -fr bundle
make bundle IMG=quay.io/aveerama/gitops-backend-operator:1.8.0-rc
make bundle-build …
```

fix: securityContext for Kam container during upgrade

---

Dockerfile
bundle/bundle.Dockerfile
config/manager/manager.yaml

> /kind bug
This PR will fix the issues w.r.t CI on release branch v1.8. Currently the build is completely broken.
NA
1. Run the operator from this branch using `make install`
2. Proceed with the regular workflow of creating `ArgoCD CR`
3. Run e2e tests locally using `make all`

fix: Unblock the build process for release branch

---

go.mod
go.sum

/kind bug
Updates argocd-operator version to include https://github.com/argoproj-labs/argocd-operator/pull/915 fix.

chore: Update argocd-operator to include ha reconciliation fix

---

go.mod
go.sum

`1-050_validate_sso_config` test is flaky due to a bug in argocd-operator which has been fixed with https://github.com/argoproj-labs/argocd-operator/pull/922. This PR updates argocd-operator version to include that fix. 
Fixes [GITOPS-2929](https://issues.redhat.com/browse/GITOPS-2929)
`1-050_validate_sso_config` test should pass consistently in openshift-ci

chore: Update argocd-operator to fix sso test failure

---

scripts/openshift-CI-kuttl-tests.sh

- adding [openshift-CI-kuttl-tests.sh](https://github.com/redhat-developer/gitops-operator/blob/master/scripts/openshift-CI-kuttl-tests.sh) scirpt from master branch
- this script acts as the entrypoint for openshift-ci kuttl tests 
Fixes https://issues.redhat.com/browse/GITOPS-2726

add openshift-ci script to run kuttl test

---

bundle/manifests/argoproj.io_applications.yaml
bundle/manifests/gitops-operator.clusterserviceversion.yaml
config/crd/bases/argoproj.io_applications.yaml
config/manifests/patches/description.yaml
go.mod
go.sum
test/openshift/e2e/sequential/1-031_validate_toolchain/01-check.yaml

Argocd-operator was [updated with the latest CRDs](https://github.com/argoproj-labs/argocd-operator/pull/944) from [Argo CD 2.7.6](https://github.com/argoproj/argo-cd/tree/v2.7.6/manifests/crds), this PR pulls in those changes and updates CRDs to match. 
NA
I know that the changes to CRDs include adding in typos but that's what's in upstream... :upside_down_face:

updated Argo CD 2.7.6 CRDs and argocd-operator

---

controllers/kam.go

> /kind bug
Fixes #563 
Closes #563 
1. Install GitOps Operator v1.8.0
2. Verify KAM version
3. Upgrade GitOps Operator to v1.9.0
4. Verify KAM version

fix: Handle kam image reconciliation during upgrades [release 1.9]

---

hack/non-olm-install/README.md
hack/non-olm-install/install-gitops-operator.sh

Improve the manifest based installation script (non-OLM installation) by removing the dependency on either `docker` or `podman` and instead using a lightweight binary `regctl` to extract the `ClusterServiceVersion` from within the bundle image. Since this binary gets automatically installed and uninstalled if not present on the host system, its easy for users to run the installation script without going through the overheads of setting up `docker` or `podman` on their host systems.
Fixes #?

Support migration to non-OLM installation and using regctl for extracting CSV info from bundle image

---

go.mod
main.go

Our log timestamp is not human readable.
Fixes #?
[GITOPS-2898: Operator logs should have human readable timestamps
](https://issues.redhat.com/browse/GITOPS-2898)
1. Have a k8s cluster running.
2. Go to gitops-operator/ directory and run `make install run`. Observe the timestamps in log are in RFC3339 format e.g. `2023-06-27T07:12:48-04:00`.

Fixed log timestamp format

---

.github/cherry-pick-bot.yml

This PR adds configuration for GCP cherry pick bot to streamline the process of back-porting PRs to release branches. This bot is already used in upstream argocd for cherry picking changes. 
**Bot Usage:**
Any PR which needs to be back-ported can be automated by commenting on the PR with
```
/cherry-pick target-branch-name
```
More details regarding bot can be found [here](https://github.com/googleapis/repo-automation-bots/tree/main/packages/cherry-pick-bot)
[GITOPS-3286](https://issues.redhat.com/browse/GITOPS-3286)
**Please install the [GCP cherry pick bot ](https://github.com/apps/gcp-cherry-pick-bot) on `redhat-developer/gitops-operator` before merging …

Add GCP cherry pick bot

---

controllers/argocd/argocd.go
controllers/argocd/argocd_test.go
docs/OpenShift GitOps Usage Guide.md
test/openshift/e2e/sequential/1-086_validate_default_argocd_role/01-assert.yaml
test/openshift/e2e/sequential/1-086_validate_default_argocd_role/02-assert.yaml
test/openshift/e2e/sequential/1-086_validate_default_argocd_role/02-install.yaml

> /kind bug
This PR is to make the default ArgoCD instance with name `openshift-gitops` in namespace `openshift-gitops` to have restricted default permissions. With default `readonly` permission, any non-admin user will be able to view the Application and other manifest resource managed by ArgoCD which can contain sensitive information. By setting the default permission to `''` this read only access can be avoided.
**Which issue(s) …

Fixed the default ArgoCD role for default instance openshift-gitops

---

bundle/manifests/argoproj.io_argocds.yaml
config/crd/bases/argoproj.io_argocds.yaml
go.mod
go.sum
test/openshift/e2e/parallel/1-104_validate_applicationset_tls_scm_volume_mount/01-assert.yaml
test/openshift/e2e/parallel/1-104_validate_applicationset_tls_scm_volume_mount/01-install.yaml

https://github.com/argoproj-labs/argocd-operator/pull/985 introduced support for custom tls cert mount into application set controller. This PR bring this change into gitops-operator.
Changes
- Update ArgoCD CRD to include new `spec.applicationSet.scmRootCaPath` field.
- Update argocd-operator commit ref in go.mod.
- Add kuttl test.
Fixes [GITOPS-3107](https://issues.redhat.com/browse/GITOPS-3107)
Test instructions same as https://github.com/argoproj-labs/argocd-operator/pull/985

feat: Add tls cert mount for appset controller

---

config/rbac/kustomization.yaml
hack/non-olm-install/install-gitops-operator.sh

/kind bug
Non OLM installation fails as the latest version of CRD manifests creates resources with `creationTimestamp="null"` this causes the builds to fail with error 
```
error: unable to decode "/tmp/gitops-operator-install-dxw9u9c/kustomize-build-output.yaml": parsing time "null" as "2006-01-02T15:04:05Z07:00": cannot parse "null" as "2006"
```
Also, updated the default version and dependent tool versions - yq, kustomize and regctl
Fixes #?

Updated default version to 1.9.2 and tools kustomize, regctl, yq

---

config/rbac/kustomization.yaml
hack/non-olm-install/README.md
hack/non-olm-install/install-gitops-operator.sh

This PR updates non-olm operator install script to setup conversion webhook for automatic migration of ArgoCD v1alpha1 CRs to v1beta1. The webhook is enabled by default and is controlled by `ENABLE_CONVERSION_WEBHOOK` env var. 
For non-olm install, webhook cert management is off-loaded to Openshift Service CA operator. The required annotations for this are already added in configs so no special handling is required in the script. 
Related [GITOPS-3040](https://issues.redhat.com/browse/GITOPS-3040)
- Installation
```bash …
```

feat: Update non-olm-install script to setup conversion webhook

---

controllers/argocd/openshift/clusterconfig_test.go
controllers/argocd/openshift/openshift_test.go
controllers/argocd_controller_test.go
controllers/gitopsservice_controller_test.go

/kind cleanup
Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
Reference: https://pkg.go.dev/testing#T.Setenv
```go
func TestFoo(t *testing.T) {
// before
os.Setenv(key, "new value")
defer os.Unsetenv(key)
// after
t.Setenv(key, "new value")
}
```

test: use `t.Setenv` to set env vars

---

hack/scripts/olm-nightly-install.sh

This PR includes the script needed to install the nightly operator bundle in a cluster. It takes the IIB id as a parameter and installs the operator using subscription (olm based).
To run the script , you have to export the IIB_ID 
`export IIB_ID=581525`
There are 2 options -i and -m (for first install on the cluster or for migrating to nightly)
`./olm-install-script -i` 
or 
`./olm-install-script -m`
Fixes #?

feat: add script for installing nightly olm operator

---

main.go

This PR adds env variable `LOG_LEVEL` to control logs level of the operator.
Fixes [GITOPS-4016](https://issues.redhat.com/browse/GITOPS-4016)
cherry-picked the changes from : https://github.com/argoproj-labs/argocd-operator/pull/1224
1. Run the following command from PR branch,
```shell
LOG_LEVEL=error make install run
```

chore: Add environment variable to change operator logging level

---

bundle/manifests/argoproj.io_applicationsets.yaml
config/crd/bases/argoproj.io_applicationsets.yaml
go.mod
go.sum
test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml

/kind bug
Update argocd-operator to https://github.com/argoproj-labs/argocd-operator/tree/v0.10.1-rc1

chore: Update argocd-operator to 1.10.1-rc to address CVEs

---

controllers/consoleplugin.go
controllers/consoleplugin_test.go

> /kind bug
Fixes #?
Enable `runOnInfra: true` in GitOpsService CR
And verify that the console-plugin pods has the correct nodeSelector label added to it.

fix: enable infra label to console-plugin deployment

---

bundle/manifests/gitops-operator.clusterserviceversion.yaml
config/manifests/bases/gitops-operator.clusterserviceversion.yaml

> /kind bug
Fixes https://issues.redhat.com/browse/GITOPS-4513

Removed duplicate CRD entry for ArgoCD, updated missing details for operator owned crds

---

bundle/manifests/gitops-operator.clusterserviceversion.yaml
config/manifests/bases/gitops-operator.clusterserviceversion.yaml

> /kind bug
Fixes https://issues.redhat.com/browse/GITOPS-4513
Manual cherry-pick of https://github.com/redhat-developer/gitops-operator/pull/678

Fixed CRDs owned by GitOps Operator in the clusterserviceversion manifest file for v1.11

---

bundle/manifests/gitops-operator.clusterserviceversion.yaml
config/manifests/bases/gitops-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/gitopsservice_controller.go

> /kind bug
- Adds the missing apiservicedefinitions for Argo Rollouts in the CSV.
NA

fix: add apiservicedefinitions for rollouts API [1.10]

---

test/e2e/gitopsservice_test.go

Remove workaround from e2e tests related to issue #148

Remove workaround from e2e tests for cluster config change related to issue #148

---

bundle/manifests/gitops-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/gitopsservice_controller.go

> /kind bug
fix: operator controller manager cannot list networkpolicies
```
E0522 18:24:17.392760       1 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: Failed to watch *v1.NetworkPolicy: failed to list *v1.NetworkPolicy: networkpolicies.networking.k8s.io is forbidden: User "system:serviceaccount:openshift-operators:openshift-gitops-operator-controller-manager" cannot list resource "networkpolicies" in API group "networking.k8s.io" at the cluster scope
```
NA
- Create the operator bundle and run it using OLM.

fix: operator controller manager cannot list networkpolicies [1.10]

---

bundle/manifests/gitops-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/gitopsservice_controller.go

> /kind bug
fix: operator controller manager cannot list networkpolicies
```
E0522 18:24:17.392760       1 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: Failed to watch *v1.NetworkPolicy: failed to list *v1.NetworkPolicy: networkpolicies.networking.k8s.io is forbidden: User "system:serviceaccount:openshift-operators:openshift-gitops-operator-controller-manager" cannot list resource "networkpolicies" in API group "networking.k8s.io" at the cluster scope
```
NA
- Create the operator bundle and run it using OLM.

fix: operator controller manager cannot list networkpolicies [1.11]

---

bundle/manifests/gitops-operator.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/gitopsservice_controller.go

> /kind bug
fix: operator controller manager cannot list networkpolicies
```
E0522 18:24:17.392760       1 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: Failed to watch *v1.NetworkPolicy: failed to list *v1.NetworkPolicy: networkpolicies.networking.k8s.io is forbidden: User "system:serviceaccount:openshift-operators:openshift-gitops-operator-controller-manager" cannot list resource "networkpolicies" in API group "networking.k8s.io" at the cluster scope
```
NA
- Create the operator bundle and run it using OLM.

fix: operator controller manager cannot list networkpolicies [1.12]

---

build/redis/sentinel_liveness.sh.tpl

> /kind bug
```
Readiness probe failed: AUTH failed: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?
```

fix: sentinal liveliness issue

---

hack/upgrade-rollouts-manager/.gitignore
hack/upgrade-rollouts-manager/README.md
hack/upgrade-rollouts-manager/go-run.sh
hack/upgrade-rollouts-manager/go.mod
hack/upgrade-rollouts-manager/go.sum
hack/upgrade-rollouts-manager/init-repo.sh
hack/upgrade-rollouts-manager/main.go
hack/upgrade-rollouts-manager/settings_template.env

A script which automatically upgrades to the latest commit of argo-rollouts-manager (Argo Rollouts operator).
When you run the script, it creates a PR like this: https://github.com/redhat-developer/gitops-operator/pull/700
See README.md within the PR for details.
**Which issue(s) this PR fixes**: 
Fixes #? N/A

Script to auto-upgrade argo-rollouts-manager to latest

---

controllers/argocd_metrics_controller.go
controllers/argocd_metrics_controller_test.go
test/openshift/e2e/ignore-tests/sequential/1-005_validate_metrics/01-assert.yaml
test/openshift/e2e/ignore-tests/sequential/1-041_validate_argocd_sync_alert/01-assert.yaml
test/openshift/e2e/sequential/1-041_validate_argocd_sync_alert/01-assert.yaml

Added "description" label to ArgoCDSyncAlert 
JIRA - https://issues.redhat.com/browse/GITOPS-2639

Add description label to ArgoCDSyncAlert

---

bundle.Dockerfile
bundle/manifests/argoproj.io_rolloutmanagers.yaml
bundle/manifests/gitops-operator.clusterserviceversion.yaml
bundle/metadata/annotations.yaml
config/crd/bases/argoproj.io_rolloutmanagers.yaml
config/rbac/role.yaml
controllers/gitopsservice_controller.go
go.mod
go.sum
main.go

Update to most recent 'argo-rollouts-manager' commit: https://github.com/argoproj-labs/argo-rollouts-manager/commit/b3e573f0e6ea3a5ec3eeba70ebb5d90e58efcd68

Update to latest commit of argo-rollouts-manager 'b3e573f0e6ea3a5ec3eeba70ebb5d90e58efcd68'

---

hack/upgrade-rollouts-manager/main.go
scripts/run-rollouts-e2e-tests.sh

This PR adds a new shell script which can be run to verify the Argo Rollouts functionality within gitops-operator.
- It runs the (cluster-scoped) E2E tests of the Argo Rollouts operator
- It runs the upstream E2E tests from the argo-rollouts repo
This PR only adds the scripts to the repo, so they can be called manually. We can add integration to CI in a separate PR.

Add script to run Rollouts tests against gitops-operator repo

---

go.mod
go.sum

/kind bug
Include https://github.com/argoproj-labs/argocd-operator/pull/1401 from the argocd-operator
Fixes https://issues.redhat.com/browse/GITOPS-4778

Include PR #1401 from argocd-operator

---

go.mod
go.sum

Update argocd operator to use released version 0.11.0

---

main.go

/kind bug
When using pre-release builds, when you  create an Argo Rollouts (install by creating a RolloutManager CR) the Rollouts Pod that is created will fail to start.
If you look at the Pods logs for the Rollout controller, you will see the following error:
```
[jgw@localhost-lan rollouts-plugin-trafficrouter-openshift]$ k logs pod/argo-rollouts-7bcddf67cf-hl8ph
time="2024-06-10T12:46:22Z" level=info msg="Argo Rollouts starting" version=vstable+737ca89
time="2024-06-10T12:46:22Z" level=info msg="Creating event broadcaster"
time="2024-06-10T12:46:22Z" level=info msg="Setting up event handlers"
time="2024-06-10T12:46:22Z" level=info msg="Setting up experiments event handlers"
time="2024-06-10T12:46:22Z" level=info …
```

Fix Rollouts plugin location URL format (v1.13)

---

controllers/argocd_metrics_controller.go

- This PR fixes the following error, when running the unit tests locally:
```
2024/01/24 09:40:13 Unable to retrieve current OCP version: Malformed version:
FAIL 
coverage: 69.8% of statements
FAIL github.com/redhat-developer/gitops-operator/controllers 0.088s
ok github.com/redhat-developer/gitops-operator/controllers/argocd 0.022s coverage: 92.9% of statements
ok github.com/redhat-developer/gitops-operator/controllers/argocd/openshift 0.015s coverage: 69.6% of statements
? github.com/redhat-developer/gitops-operator/version [no test files]
ok github.com/redhat-developer/gitops-operator/controllers/util 0.012s coverage: 16.7% of statements
FAIL
make: *** [Makefile:113: test] Error 1
Error: Process …
```

Fix 'Unable to retrieve current OCP version: Malformed version' when running unit tests

---

scripts/run-rollouts-e2e-tests.sh

/kind bug
- At present, the 'run-rollouts-e2e-tests.sh' script should fail when one of the child test suite fails
- The 'set -e' check was missing which should have been present initially, I have added it

'run-rollouts-e2e-tests.sh' should fail outright when an individual test fails

---

hack/upgrade-rollouts-manager/README.md
hack/upgrade-rollouts-manager/main.go

Minor tweaks to improve the script which is used to upgrade the rollouts-manager dependency in gitops-operator repo

Minor fixes to update-rollouts-manager script

---

.github/workflows/codegen.yaml

- Add a new GitHub action to verify that PR contributors have run `make manifests` `make bundle` and `make manifests` and contributed the result.
- This works with the changes made previously to ensure operator-sdk version is as expected.

Add a GitHub check to ensure consistency of generated manifests

---

bundle/manifests/argoproj.io_analysisruns.yaml
bundle/manifests/argoproj.io_analysistemplates.yaml
bundle/manifests/argoproj.io_clusteranalysistemplates.yaml
bundle/manifests/argoproj.io_experiments.yaml
bundle/manifests/argoproj.io_rolloutmanagers.yaml
bundle/manifests/argoproj.io_rollouts.yaml
config/crd/bases/analysis-run-crd.yaml
config/crd/bases/analysis-template-crd.yaml
config/crd/bases/argoproj.io_rolloutmanagers.yaml
config/crd/bases/cluster-analysis-template-crd.yaml
config/crd/bases/experiment-crd.yaml
config/crd/bases/rollout-crd.yaml
go.mod
go.sum
scripts/run-rollouts-e2e-tests.sh
test/openshift/e2e/sequential/1-101_validate_rollout_policyrules/01-assert.yaml

Update to most recent 'argo-rollouts-manager' commit: https://github.com/argoproj-labs/argo-rollouts-manager/commit/192dd2c3b5dd026e2c59c5765e98ca2f70ca01f9

Update to latest commit of argo-rollouts-manager '192dd2c3b5dd026e2c59c5765e98ca2f70ca01f9'

---

scripts/run-rollouts-e2e-tests.sh

- This adds runs the E2E tests from https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-openshift on gitops-operator

Add OpenShift Rollouts Route Plugin E2E tests to GitOps Operator tests

---

controllers/argocd_metrics_controller_test.go
controllers/gitopsservice_controller.go
controllers/gitopsservice_controller_test.go

/kind bug
JIRA - https://issues.redhat.com/browse/GITOPS-4185
We were not able to patch the NodePlacement directly through ArgoCD CR, if we do,  it removes the nodePlacement from ArgoCD CR while reconciling because of this https://github.com/redhat-developer/gitops-operator/blob/master/controllers/gitopsservice_controller.go#L475 here `defaultArgoCDInstance.Spec.NodePlacement` is nil as it not getting updated anywhere else in code, `defaultArgoCDInstance.Spec.NodePlacement` is only getting updated if we update it through  GitOpsService CR or else it  update `existingArgoCD.Spec.NodePlacement` as nil because of the reason I have mentioned above  , but if a user wants to add custom nodePlacement he/she should patch nodePlacement through GitOpsService CR and it …

Fix bug where ArgoCD removes nodePlacement stanza from configuration

---

controllers/dashboards/gitops-rollouts.json
docs/OpenShift GitOps Usage Guide.md

> /kind bug
This PR adds a new dashboard to the OpenShift Console for Rollouts. It leverages the metrics provided by the operator deployed servicemonitor for Rollouts. This dashboard is based on the upstream Argo Rollouts dashboard but tuned and tweaked for the Console.
* [ *] Documentation update is required by this PR.
No issue has been opened for this but can open one if needed.
* [*] …

Add dashboard for Rollouts

---

go.mod
go.sum

/kind bug
- Update argocd-operator dependency to latest from `master` branch, to pick up https://github.com/argoproj-labs/argocd-operator/pull/1469
N/A

Upgrade Argo CD Operator to pick up TLS race cond fix

---

test/e2e/suite_test.go
test/nondefaulte2e/suite_test.go

/kind code-refactoring
Non-kuttl test execution was removed in a previous [PR ](https://github.com/redhat-developer/gitops-operator/pull/611/files)as the 'printer' package is no longer available in "sigs.k8s.io/controller-runtime/pkg/envtest/printer"
Which issue(s) this PR fixes:
Fixes #?
[GITOPS-4777](https://issues.redhat.com/browse/GITOPS-4777)
How to test changes / Special notes to the reviewer:
make test-e2e should now execute (without RunSpecsWithDefaultAndCustomReporters)

Enable e2e tests

---

controllers/gitopsservice_controller.go

fix: ensure pod security label on namespace

---

bundle/manifests/gitops-operator.clusterserviceversion.yaml
config/manager/manager.yaml

/kind bug
During the operator-sdk upgrade, we set resource limits for the manager container. However, these limits are causing issues for users, particularly on clusters with a large number of secrets and configmaps, as the operator requires significantly more memory to function, leading to OOM kills. We are currently exploring ways to reduce memory consumption, however, this involves significant effort. Therefore, this PR removes the limits to minimize the impact.
Fixes [GITOPS-5665](https://issues.redhat.com/browse/GITOPS-5665)
I have tested this change using the reproducer from JIRA. The operator was functioning properly, …

fix: Remove resource limits for manager container

---

go.mod
go.sum

/kind bug
- Upgrade to latest version of Argo Rollouts v0.0.4.1 to address issues identified when switching from cluster/namespace-scoped Rollouts installs
Fixes #?

Upgrade v1.14 to Argo Rollouts manager v0.0.4.1: df262fe66d25638de47ee98130dcebe016c8fae5

---

go.mod
go.sum
test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml

/kind cleanup
This PR updates argocd and argocd-operator version

update argocd-operator version for release 1.14.1

---

go.mod
go.sum
scripts/run-rollouts-e2e-tests.sh
test/openshift/e2e/sequential/1-100_validate_rollouts_resources_creation/01-assert.yaml
test/openshift/e2e/sequential/1-100_validate_rollouts_resources_creation/01-install-rolloutmanager.yaml
test/openshift/e2e/sequential/1-100_validate_rollouts_resources_creation/02-assert.yaml
test/openshift/e2e/sequential/1-101_validate_rollout_policyrules/01-install-rollloutmanager.yaml

Update to most recent 'argo-rollouts-manager' commit: https://github.com/argoproj-labs/argo-rollouts-manager/commit/52fd4a22e49e9bb0a3947262cce75931b63b209b

Update to latest commit of argo-rollouts-manager '52fd4a22e49e9bb0a3947262cce75931b63b209b'

---

scripts/run-rollouts-e2e-tests.sh

/kind bug
- Rollouts E2E test script should point to v0.0.4.1 branch
N/A

Rollouts E2E test script should point to v0.0.4.1 branch

---

test/openshift/e2e/sequential/1-020_validate_redis_ha_nonha/04-disable-ha.yaml

/kind bug
- Fix typo in YAML for 1-020_validate_redis_ha_nonha
- I somewhat suspect this is causing tests after it that depend on `openshift-gitops` namespace to break (e.g. `1-041_validate_argocd_sync_alert`)

Fix typo in YAML for 1-020_validate_redis_ha_nonha

---

test/openshift/e2e/sequential/1-034_validate_custom_roles/06-revert-patch.yaml

Fix failing of 1-040_validate_quoted_RBAC_group_names test

---

test/openshift/e2e/parallel/1-052_validate_rolebinding_number/02-check_rolebindings.yaml

Fixes race condition in e2e test 1-052_validate_rolebinding_number. As per Jonathan's request:
- '02-check_rolebindings.yaml' should loop wait, rather than only running once then failing:
- first it should loop, waiting for the expected number of rolebindings exist (e.g. similar to an 'Eventually' in ginkgo)
- then it should loop, waiting that the expected number of rolebindings continue to exists for 20 seconds (similar to 'Consistently' in ginkgo)

Fix race condition in e2e test 1-052_validate_rolebinding_number

---

bundle/manifests/argoproj.io_applications.yaml
bundle/manifests/gitops-operator.clusterserviceversion.yaml
config/crd/bases/argoproj.io_applications.yaml
go.mod
go.sum
test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml

/kind chore
Upgrade argocd-operator versions

chore: Upgrade argocd-operator versions

---

.ci-operator.yaml
Dockerfile
go.mod
openshift-ci/build-root/Dockerfile
test/openshift/e2e/ignore-tests/parallel/1-066_validate_redis_secure_comm_no_autotls_no_ha/02-generate_cert.yaml
test/openshift/e2e/ignore-tests/parallel/1-067_validate_redis_secure_comm_no_autotls_ha/02-generate_cert.yaml
test/openshift/e2e/parallel/1-066_validate_redis_secure_comm_no_autotls_no_ha/02-generate_cert.yaml
test/openshift/e2e/parallel/1-067_validate_redis_secure_comm_no_autotls_ha/02-generate_cert.yaml

chore: Bump go to 1.22

---

go.mod
go.sum
scripts/run-rollouts-e2e-tests.sh

Update to most recent 'argo-rollouts-manager' commit: https://github.com/argoproj-labs/argo-rollouts-manager/commit/9f79ece2e923cbf03fe041bb6d1d83aae16a08da

Update to latest commit of argo-rollouts-manager '9f79ece2e923cbf03fe041bb6d1d83aae16a08da'

---

go.mod
go.sum

This reverts commit ccad01fe765236f028538354d663d3b3421b2de1.
> /kind bug
Fixes #?

Revert "update argo rollout manager (#813)"

---

test/openshift/e2e/parallel/1-057_validate_notifications/05-verify-email.yaml

Fixes race condition in e2e test 1-057_validate_notifications. 
**Fixes**
RH issue tracker :- https://issues.redhat.com/browse/GITOPS-5968

fix: race condition in e2e test 1-057_validate_notifications

---

scripts/run-rollouts-e2e-tests.sh

As of latest release of Argo Rollouts, we now require CLUSTER_SCOPED_ARGO_ROLLOUTS_NAMESPACES to be set if user is installing outside the openshift-gitops Namespace. 
This requirement broke the Rollouts E2E tests when running via the `run-rollouts-e2e-tests.sh` script in gitops-operator.
The fix is to add/remove the appropriate value from the Subscription (or Deployment).
**Code reviewer guidelines**:
If you install OpenShift GitOps via subscription on clusterbot-style cluster, then run the script, it should pass. 
The other mode (run via CI) isn't supported at the moment, as the …

Fix cluster-scoped runs within gitops-operator Rollouts E2E test script

---

test/e2e/argocd_metrics_test.go
test/e2e/gitopsservice_test.go

/kind code-refactoring
I noticed that this test was failing in another PR:
```
[91m[1m[Fail] [0m[90mArgo CD metrics controller [0m[0mCheck if monitoring resources are created [0m[91m[1m[It] Role is created [0m
[37m/go/src/github.com/redhat-developer/gitops-operator/test/e2e/argocd_metrics_test.go:42[0m
```
However, it was not obvious why, because the output from oc is not printed in the failing case. This PR updates the command execution logic to output console stdout/stderr, so if this error occurs again we can know why.

Add additional debugging to test command execution

---

bundle/manifests/gitops-operator.clusterserviceversion.yaml
go.mod
go.sum
scripts/run-rollouts-e2e-tests.sh

Update to most recent 'argo-rollouts-manager' commit: https://github.com/argoproj-labs/argo-rollouts-manager/commit/b4635b5b8dd1f9683a25df512fec7169cab4403c

Update to latest commit of argo-rollouts-manager 'b4635b5b8dd1f9683a25df512fec7169cab4403c'

---

go.mod
go.sum

This PR is to update argocd-operator version.

chore: update argocd-operator version

---

test/openshift/e2e/sequential/1-035_validate_argocd_secret_repopulate/05-argocd_login.yaml
test/openshift/e2e/sequential/1-040_validate_quoted_RBAC_group_names/01-login_argocd_api_server.yaml

Recent changes with argocd CLI requires `--skip-test-tls` to be added as an option while connecting to argocd server. This will be a temporary fix until the upstream issue is resolved
Fixes #?

Fix interop test failures

---

controllers/argocd/openshift/openshift.go
controllers/argocd/openshift/openshift_test.go

Update argocd operator commit for adding missing permission in application controller clusterrole
Fixes #?

fix: Add missing impersonate rule

---

bundle/manifests/argoproj.io_analysisruns.yaml
bundle/manifests/argoproj.io_analysistemplates.yaml
bundle/manifests/argoproj.io_clusteranalysistemplates.yaml
bundle/manifests/argoproj.io_experiments.yaml
bundle/manifests/argoproj.io_rollouts.yaml
config/crd/bases/analysis-run-crd.yaml
config/crd/bases/analysis-template-crd.yaml
config/crd/bases/cluster-analysis-template-crd.yaml
config/crd/bases/experiment-crd.yaml
config/crd/bases/rollout-crd.yaml
go.mod
go.sum
scripts/run-rollouts-e2e-tests.sh

/kind cleanup
This PR re-targets GitOps Operator v1.16 to use Argo Rollouts Manager v0.0.5 (the most recent stable release of Argo Rollouts Manager). The corresponding Argo Rollouts version is v1.7.2.

Downgrade v1.16 to Argo Rollouts Manager v0.0.5

---

scripts/run-rollouts-e2e-tests.sh

This updates v1.15 E2E test script to use backported fixes to E2E tests. The actual version of Rollouts Manager (operator) still remains the same.

Update v1.15 branch to point to Rollouts E2E test fixes

---

go.mod
go.sum

/kind bug
Update argocd-operator to include the fix for [GITOPS-6495](https://issues.redhat.com/browse/GITOPS-6495)
Fixes [GITOPS-6495](https://issues.redhat.com/browse/GITOPS-6495)

GITOPS-6495 fix for cmp server crashing with busybox image (#865)

---

go.mod
go.sum
scripts/run-rollouts-e2e-tests.sh

- Fix failing E2E Rollouts test script when run standalone, by updating to latest Argo Rollouts Manager test commit.

Update to latest commit of argo-rollouts-manager 'bb5580b286c595f91dfc21382df494e5fb8f9a46'

---

scripts/run-rollouts-e2e-tests.sh

- Pick up this commit from Argo Rollouts operator E2E test script:
https://github.com/argoproj-labs/argo-rollouts-manager/commit/ee5dc2da6990ba257bf71dee279c14efeec124c0#diff-c633bb4c06830e58514630b546b8ddb0b1eaaa58c34a64a993ce5565f4346e61
- This enables a fix for running Argo Rollouts upstream E2E tests on non-x64 platforms (it was previously fixed, but I broke it :smile: )

Re-enable fix for multi-arch Argo Rollouts E2E test images (v1.16)

---

controllers/argocd_metrics_controller.go
controllers/argocd_metrics_controller_test.go

argocd adds cluster monitoring label if the ns contains openshift- prefix
/kind bug
This PR fixes the namespace isolation break, caused by using cluster-monitoring label for monitoring 
Fixes  [GITOPS-6251](https://issues.redhat.com/browse/GITOPS-6251)

[1.14] fix CVE namespace-isolation break CVE-13484

---

scripts/run-rollouts-e2e-tests.sh

- Pick up this commit from Argo Rollouts operator E2E test script:
https://github.com/argoproj-labs/argo-rollouts-manager/commit/836ab677ea4d20a39a16c9f7c8162827cd259ee8
- This enables a fix for running Argo Rollouts upstream E2E tests on non-x64 platforms (it was previously fixed, but I broke it :smile: )

Re-enable fix for multi-arch Argo Rollouts E2E test images (master branch)

---

scripts/run-rollouts-e2e-tests.sh

/kind bug
Updates Argo Rollouts E2E test script to point to latest version of Rollouts tests. This commit includes that fix for multi-arch Rollouts images.

Update v1.15 branch to argo-rollouts E2E tests latest v1.15 branch scripts

---

test/examples/nginx/nginx.yaml

/kind bug
- At present our E2E tests are using `nginxinc/nginx-unprivileged` from Docker Hub. Unfortunately, Docker Hub has strict rate-limiting for unauthenticated users.
- Fortunately, the nginx open source project maintains `nginx-unprivileged` image on quay.io.
- I've verified that the E2E tests still pass with new image location.

Switch to quay.io repo for nginx-unprivileged image to avoid docker hub rate limiting

---

go.mod
go.sum

bump github.com/argoproj-labs/argocd-operator to v0.14.1-0.20250417144336-f66b337d3325
Ref commit that is picked up by this version bump- https://github.com/argoproj-labs/argocd-operator/commit/f66b337d3325856099b64f3908383e84823c564e

GITOPS-6759: bump github.com/argoproj-labs/argocd-operator 

---

go.mod
go.sum

/kind bug
Update Argo CD Operator to latest https://github.com/argoproj-labs/argocd-operator/commit/168deb59ac7f074b43c1147e28a942e5afaa643e

chore: Update argocd-operator to latest for v1.15.3

---

test/openshift/e2e/README.md

Add instructions for running/developing the Ginkgo-based E2E tests.

Add Ginkgo test instructions via README.md

---

bundle/manifests/gitops-operator.clusterserviceversion.yaml
go.mod
go.sum
scripts/run-rollouts-e2e-tests.sh

Update to most recent 'argo-rollouts-manager' commit: https://github.com/argoproj-labs/argo-rollouts-manager/commit/ebd6207c8bb1352eac450307573fdb0dbd5e7bd0
- The only update is an E2E test change, switching to quay.io from docker hub, to avoid rate limiting.

Update to latest commit of argo-rollouts-manager 'ebd6207c8bb1352eac450307573fdb0dbd5e7bd0'

---

scripts/run-rollouts-e2e-tests.sh

A fix for a race condition in the Argo Rollouts Route plugin E2E tests was made as part of https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-openshift/commit/1495bbad184a05cde955fb21dcf35d05c3e58d98
This PR adopts that commit to run it as part of gitops-operator rollouts E2E tests.
N/A

Update to latest version of Argo Rollouts Route plugin E2E tests on 'v1.16' branch

---

test/openshift/e2e/README.md

- Updates to E2E test docs, which provide more detail and answers common questions
- PR is doc update only

Update Ginkgo E2E test docs

---

cmd/main.go
controllers/argocd/openshift/openshift.go
controllers/argocd/openshift/openshift_test.go

Currently, we copy the rules from the admin cluster role when creating the application controller role. However, any updates to the admin cluster role are not synced to the application controller cluster role. So, the application controller may not have permissions to manage certain resources until the next reconciliation cycle.
Dependent on: https://github.com/argoproj-labs/argocd-operator/pull/1775
Fixes https://issues.redhat.com/browse/GITOPS-6367
1. Run the operator
2. Create a namespace with the managed-by label
3. Install any …

feat: watch and reconcile updates to the admin clusterrole

---

Makefile
controllers/gitopsservice_controller.go
test/openshift/e2e/ginkgo/sequential/1-018_validate_disable_default_instance_test.go

/kind bug
Before these changes, deleting the default ArgoCD instance (openshift-gitops) did not trigger its automatic recreation. However, with these changes, the default instance is now correctly recreated when it is deleted.
No documentation required.
https://issues.redhat.com/browse/GITOPS-7475
Fixes #?
Deploy the GitOps Operator, then delete the default openshift-gitops instance from the openshift-gitops namespace. Verify if the …

[GITOPS-7475]: Default argocd instance does not get recreated after deletion

---

test/openshift/e2e/ginkgo/parallel/1-115_validate_controller_extra_command_args_test.go
test/openshift/e2e/ginkgo/parallel/1-120_validate_resource_health_persisted_in_application_status_test.go

e2e test for https://github.com/argoproj-labs/argocd-operator/pull/1763 and https://github.com/argoproj-labs/argocd-operator/pull/1722 
Will make few more changes if needed once this [PR](https://github.com/redhat-developer/gitops-operator/pull/918) is merged

Add e2e ginkgo tests for extraCommandargs and Application Health Status
